$axure.loadCurrentPage({
  "url":"meadmin_details_class_headerfoot.html",
  "generationDate":new Date(1396297425036.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c670a9b80a6a48b4b238a7895be12d3e",
    "type":"Axure:Page",
    "name":"MeAdmin_Details_Class_headerfoot",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkFrame",
                "description":"Open MeAdmin_Details_programme_progress in grid_frame_01",
                "linkType":"frame",
                "framesToTargets":[{
                    "framePath":["42036ac036544121b889db0dee928476"],
                    "target":{
                      "targetType":"page",
                      "url":"meadmin_details_programme_progress.html",
                      "includeVariables":true}}]},
{
                "action":"setFunction",
                "description":"Set is selected of progress equal to &quot;true&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["beda9e50c937466a9f65f03c801a7209"]},
{
                          "exprType":"stringLiteral",
                          "value":"true",
                          "stos":[]}]}]}}]}]}},
    "diagram":{
      "objects":[{
          "id":"1f7a5cc7e741468db04345844acbca4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "size":{
              "width":899,
              "height":608},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":2,
              "color":{
                "r":51,
                "g":51,
                "b":51,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11e9eb3ed82c45d29f5ee59d6555efe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "size":{
                  "width":899,
                  "height":608},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":2,
                  "color":{
                    "r":51,
                    "g":51,
                    "b":51,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u0.png"}},
{
          "id":"4fef6e6516c347f290f397f40d3c21fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFCECECE},
{
                  "color":0xFFCECECE}]},
            "size":{
              "width":900,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57f1a2d03a55468696f34383f8e24cd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFCECECE},
{
                      "color":0xFFCECECE}]},
                "size":{
                  "width":900,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u4.png"}},
{
          "id":"79c831d9a2ff4c38be8f6df8f1683225",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Fet', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":28,
              "y":6},
            "size":{
              "width":48,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da30f2e37aa74fb991504a8d4ddc040c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Fet', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":6},
                "size":{
                  "width":48,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56524483db3b45cd936c629b905c5db4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":6},
            "size":{
              "width":13,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f16012fa08840b9b8112f334227a032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":6},
                "size":{
                  "width":13,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u8.png"}},
{
          "id":"e075e77ef1df43fca37443a6fc0e8b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1EE},
            "location":{
              "x":1,
              "y":25},
            "size":{
              "width":897,
              "height":41},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e25e581a75542c6a879f206e95aa9fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1EE},
                "location":{
                  "x":1,
                  "y":25},
                "size":{
                  "width":897,
                  "height":41},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u8.png"}},
{
          "id":"43f6be4cf036422b8107843e2475f3bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":318,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7c25a09c31643e3943ded7b7a923b1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":318,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31bb0165514c48908162c7713ee418ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC5C5C5},
            "location":{
              "x":0,
              "y":571},
            "size":{
              "width":899,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b302365985c44e1c81577b15fd9ef33c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC5C5C5},
                "location":{
                  "x":0,
                  "y":571},
                "size":{
                  "width":899,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u2.png"}},
{
          "id":"0a0864c915c64fc58b37bfda30c25b8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF464646,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2}]},
            "location":{
              "x":9,
              "y":575},
            "size":{
              "width":84,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56795fde551340238ac49f4065c49dcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF464646,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2}]},
                "location":{
                  "x":9,
                  "y":575},
                "size":{
                  "width":84,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_class_headerfoot/u14.png"}},
{
          "id":"caa3a129eda749e7893fd4902887aede",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF464646,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2}]},
            "location":{
              "x":823,
              "y":575},
            "size":{
              "width":65,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"003ff9a7ec6942c49b8d872978cba11c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF464646,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2}]},
                "location":{
                  "x":823,
                  "y":575},
                "size":{
                  "width":65,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u14.png"}},
{
          "id":"e06ff81c1e844859a7eaf78d615a30de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF464646,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2}]},
            "location":{
              "x":98,
              "y":575},
            "size":{
              "width":93,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99e20169403249beb1f23345a684bdcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF464646,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2}]},
                "location":{
                  "x":98,
                  "y":575},
                "size":{
                  "width":93,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u16.png"}},
{
          "id":"c9eaa682be584e14b44f1f9ac3fdac95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":40,
              "y":48},
            "size":{
              "width":296,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"650d3de7e3404e93ba5709b0016a1db7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":48},
                "size":{
                  "width":296,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68c2e15d67644c27b0de20228e989340",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":32},
            "size":{
              "width":27,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05e750e0dc3b4cdeb1eb757dc24ca622",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":32},
                "size":{
                  "width":27,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u20.png"}},
{
          "id":"fc7c71aa813c4c20ac456747f66eea39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF464646,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2}]},
            "location":{
              "x":831,
              "y":29},
            "size":{
              "width":58,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"876c8fc004974921b3b2d6a37eeaba65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF464646,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2}]},
                "location":{
                  "x":831,
                  "y":29},
                "size":{
                  "width":58,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle RCmenu_001",
                      "objectsToFades":[{
                          "objectPath":["542a07121b5045a38f0963508c604030"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u35.png"}},
{
          "id":"b2012a7e19454fb69ed93759758ffed4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":838,
              "y":34},
            "size":{
              "width":7,
              "height":7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17700ec58d2f459a987ec56b657425ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":838,
                  "y":34},
                "size":{
                  "width":7,
                  "height":7}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle RCmenu_001",
                      "objectsToFades":[{
                          "objectPath":["542a07121b5045a38f0963508c604030"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u37.png"}},
{
          "id":"542a07121b5045a38f0963508c604030",
          "label":"RCmenu_001",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":703,
              "y":29},
            "size":{
              "width":101,
              "height":186},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4836cd433e3141e08b2a11e8ccb45ee1",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":101,
                  "height":186}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ddb1a4acbac4007a76ecf808c8233a2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"6px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":101,
                      "height":20},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab1e6821ddda49918ee868a2ed8d9000",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":101,
                          "height":20},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e7de2ea3ed904ddca4db1e5f5ab890cd",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"6px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":101,
                      "height":21},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93fa7b5010f14a8597aabf674873409b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":102},
                        "size":{
                          "width":101,
                          "height":21},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4029ccce828343f9ace7fb2c3bc38389",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"6px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":101,
                      "height":21},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f48f3f9293664abeb886853faba7d3ac",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":101,
                          "height":21},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5460869bc0ef45bda9d7aee90a1b2519",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"6px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":81},
                    "size":{
                      "width":101,
                      "height":21},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1580ddadddbd4235822b83096ca75ac2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":81},
                        "size":{
                          "width":101,
                          "height":21},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"267949183c8e4bc6a76a5f68eb9e3c7d",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"6px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":123},
                    "size":{
                      "width":101,
                      "height":21},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bb60322b8c03455ba5e34f45c86d7c1c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":123},
                        "size":{
                          "width":101,
                          "height":21},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a058c51c90f543b196e54e3df0c6db46",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"6px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":144},
                    "size":{
                      "width":101,
                      "height":21},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b31cf087ec94b2193c090e1dbb5bf17",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":101,
                          "height":21},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bcc7f82901ae4c1d9d2cdab660cc0f0c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"6px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":165},
                    "size":{
                      "width":101,
                      "height":21},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84f53204c3b14220afcc2a546ab7291e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":165},
                        "size":{
                          "width":101,
                          "height":21},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9962f3f2d14f418ba10b7785430628a9",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"6px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":101,
                      "height":20},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"600b8c9cc4cf4787b331baee0853c790",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":101,
                          "height":20},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"598228ec1ba24d26a9580b5f94469a50",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"6px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":101,
                      "height":20},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a50fd61812524915bb3de654ba0abfef",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":101,
                          "height":20},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"105bf40427a24448ac823ff5d60c4d9b",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":101,
                  "y":123},
                "size":{
                  "width":96,
                  "height":40},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3bf9841b23d840c8b8382e4b70c727cd",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":96,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce6aa6e6fd99443ebb029cad3fe7e6fa",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":96,
                          "height":20},
                        "limbo":false,
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"23be619e8c5445bf98d355f0a5112002",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"10px",
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF666666,
                              "opacity":1},
                            "lineSpacing":"6px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":96,
                              "height":20},
                            "limbo":false,
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkFrame",
                                  "description":"Open Link in Frame",
                                  "linkType":"frame",
                                  "framesToTargets":[]}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"resources/images/transparent.gif"}},
{
                      "id":"0b677b049bcf489f9f8b7d5e3836b256",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":96,
                          "height":20},
                        "limbo":false,
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8bb0c57d86f34fb093bc5a981c9e1a12",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"10px",
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF666666,
                              "opacity":1},
                            "lineSpacing":"6px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":20},
                            "size":{
                              "width":96,
                              "height":20},
                            "limbo":false,
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkFrame",
                                  "description":"Open Link in Frame",
                                  "linkType":"frame",
                                  "framesToTargets":[]}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}]}],
              "parentCellId":"267949183c8e4bc6a76a5f68eb9e3c7d"},
{
              "id":"591f84e54c2b440eb16311e7be8aaa5d",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":101,
                  "y":165},
                "size":{
                  "width":59,
                  "height":40},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ba20a4c7da2c4d7da2880fea7cf3ea68",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":59,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"31f4e919c25543c395805ee14272b722",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":59,
                          "height":20},
                        "limbo":false,
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"108c9184326941edb5c3a7b1e1cd4fc9",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"10px",
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF666666,
                              "opacity":1},
                            "lineSpacing":"6px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":59,
                              "height":20},
                            "limbo":false,
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}},
{
                      "id":"4df123ca6437443e923a9ca0c05b00da",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":59,
                          "height":20},
                        "limbo":false,
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e626c4ef23364b30adb167b5f8006dc4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"10px",
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF666666,
                              "opacity":1},
                            "lineSpacing":"6px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":20},
                            "size":{
                              "width":59,
                              "height":20},
                            "limbo":false,
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}]}],
              "parentCellId":"bcc7f82901ae4c1d9d2cdab660cc0f0c"},
{
              "id":"b6db923343604650aeabb3da5cbc9706",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":101,
                  "y":144},
                "size":{
                  "width":100,
                  "height":80},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a107dfe5c1f64241a181254683c9f5a4",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af3c0b35fcc546658db545805a44390a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":20},
                        "limbo":false,
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1ed0243533c94db39ae53e67b07c44aa",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"10px",
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF666666,
                              "opacity":1},
                            "lineSpacing":"6px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":100,
                              "height":20},
                            "limbo":false,
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}},
{
                      "id":"0a9f28d4de734685aa4a175ce97b9fa9",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":100,
                          "height":20},
                        "limbo":false,
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a31c8dcfeeb144089bfc7e5f8bf441d8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"10px",
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF666666,
                              "opacity":1},
                            "lineSpacing":"6px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":20},
                            "size":{
                              "width":100,
                              "height":20},
                            "limbo":false,
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}},
{
                      "id":"81ef9b346cbe4e389d5bec700a58d0a7",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":100,
                          "height":20},
                        "limbo":false,
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ab8d86740cb145268042df1d0d94b28b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"10px",
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF666666,
                              "opacity":1},
                            "lineSpacing":"6px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":40},
                            "size":{
                              "width":100,
                              "height":20},
                            "limbo":false,
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}},
{
                      "id":"b5d2a6ee14a04d078ac38c5b00fc9665",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"6px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":100,
                          "height":20},
                        "limbo":false,
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fdfaec880ba443f9a07c5a2717254501",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"10px",
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF666666,
                              "opacity":1},
                            "lineSpacing":"6px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":60},
                            "size":{
                              "width":100,
                              "height":20},
                            "limbo":false,
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}]}],
              "parentCellId":"a058c51c90f543b196e54e3df0c6db46"}]},
{
          "id":"42036ac036544121b889db0dee928476",
          "label":"grid_frame_01",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":89},
            "size":{
              "width":899,
              "height":483}},
          "adaptiveStyles":{
}},
{
          "id":"ba21e85d96374c4eb987f80fd698f14f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFCECECE},
{
                  "color":0xFFCECECE}]},
            "location":{
              "x":0,
              "y":65},
            "size":{
              "width":900,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"284d115c9d3b4d5ca6f96e9e384b3a21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFCECECE},
{
                      "color":0xFFCECECE}]},
                "location":{
                  "x":0,
                  "y":65},
                "size":{
                  "width":900,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u23.png"}},
{
          "id":"cea065e1d89b4d96a7cac1fda7ae5936",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Fet', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":11,
              "y":71},
            "size":{
              "width":102,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ebb1e803e8418c91541f337991a609",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Fet', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":71},
                "size":{
                  "width":102,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"beda9e50c937466a9f65f03c801a7209",
          "label":"progress",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}},
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFB9BCC4},
            "location":{
              "x":792,
              "y":68},
            "size":{
              "width":104,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3db83cd007a841b489a3367473a2414f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}},
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFB9BCC4},
                "location":{
                  "x":792,
                  "y":68},
                "size":{
                  "width":104,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"Open MeAdmin_Details_programme_progress in grid_frame_01",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["42036ac036544121b889db0dee928476"],
                          "target":{
                            "targetType":"page",
                            "url":"meadmin_details_programme_progress.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot_1/progress_u27.png",
            "selected~":"images/meadmin_details_educ_entity_headerfoot_1/progress_u27_selected.png",
            "mouseOver~":"images/meadmin_details_educ_entity_headerfoot_1/progress_u27_selected.png"}},
{
          "id":"ee86e3a2132b40898ac5141d97197d02",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":82},
            "size":{
              "width":899,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8B9BA8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/meadmin_details_educ_entity_headerfoot/u29_line.png"}},
{
          "id":"8f02b7ef713445199b448fbd038870f5",
          "label":"members",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}},
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFB9BCC4},
            "location":{
              "x":701,
              "y":68},
            "size":{
              "width":96,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"089b4dd16e3348239746f7620ef1097e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}},
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFB9BCC4},
                "location":{
                  "x":701,
                  "y":68},
                "size":{
                  "width":96,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"Open MeAdmin_Details_programme_contact in grid_frame_01",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["42036ac036544121b889db0dee928476"],
                          "target":{
                            "targetType":"page",
                            "url":"meadmin_details_programme_contact.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot_1/members_u30.png",
            "selected~":"images/meadmin_details_educ_entity_headerfoot_1/members_u30_selected.png",
            "mouseOver~":"images/meadmin_details_educ_entity_headerfoot_1/members_u30_selected.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1f7a5cc7e741468db04345844acbca4c":{
      "scriptId":"u0"},
    "11e9eb3ed82c45d29f5ee59d6555efe1":{
      "scriptId":"u1"},
    "4fef6e6516c347f290f397f40d3c21fa":{
      "scriptId":"u2"},
    "57f1a2d03a55468696f34383f8e24cd4":{
      "scriptId":"u3"},
    "79c831d9a2ff4c38be8f6df8f1683225":{
      "scriptId":"u4"},
    "da30f2e37aa74fb991504a8d4ddc040c":{
      "scriptId":"u5"},
    "56524483db3b45cd936c629b905c5db4":{
      "scriptId":"u6"},
    "2f16012fa08840b9b8112f334227a032":{
      "scriptId":"u7"},
    "e075e77ef1df43fca37443a6fc0e8b2a":{
      "scriptId":"u8"},
    "8e25e581a75542c6a879f206e95aa9fc":{
      "scriptId":"u9"},
    "43f6be4cf036422b8107843e2475f3bf":{
      "scriptId":"u10"},
    "a7c25a09c31643e3943ded7b7a923b1f":{
      "scriptId":"u11"},
    "31bb0165514c48908162c7713ee418ef":{
      "scriptId":"u12"},
    "b302365985c44e1c81577b15fd9ef33c":{
      "scriptId":"u13"},
    "0a0864c915c64fc58b37bfda30c25b8d":{
      "scriptId":"u14"},
    "56795fde551340238ac49f4065c49dcc":{
      "scriptId":"u15"},
    "caa3a129eda749e7893fd4902887aede":{
      "scriptId":"u16"},
    "003ff9a7ec6942c49b8d872978cba11c":{
      "scriptId":"u17"},
    "e06ff81c1e844859a7eaf78d615a30de":{
      "scriptId":"u18"},
    "99e20169403249beb1f23345a684bdcb":{
      "scriptId":"u19"},
    "c9eaa682be584e14b44f1f9ac3fdac95":{
      "scriptId":"u20"},
    "650d3de7e3404e93ba5709b0016a1db7":{
      "scriptId":"u21"},
    "68c2e15d67644c27b0de20228e989340":{
      "scriptId":"u22"},
    "05e750e0dc3b4cdeb1eb757dc24ca622":{
      "scriptId":"u23"},
    "fc7c71aa813c4c20ac456747f66eea39":{
      "scriptId":"u24"},
    "876c8fc004974921b3b2d6a37eeaba65":{
      "scriptId":"u25"},
    "b2012a7e19454fb69ed93759758ffed4":{
      "scriptId":"u26"},
    "17700ec58d2f459a987ec56b657425ae":{
      "scriptId":"u27"},
    "542a07121b5045a38f0963508c604030":{
      "scriptId":"u28"},
    "4836cd433e3141e08b2a11e8ccb45ee1":{
      "scriptId":"u29"},
    "9ddb1a4acbac4007a76ecf808c8233a2":{
      "scriptId":"u30"},
    "ab1e6821ddda49918ee868a2ed8d9000":{
      "scriptId":"u31"},
    "9962f3f2d14f418ba10b7785430628a9":{
      "scriptId":"u32"},
    "600b8c9cc4cf4787b331baee0853c790":{
      "scriptId":"u33"},
    "598228ec1ba24d26a9580b5f94469a50":{
      "scriptId":"u34"},
    "a50fd61812524915bb3de654ba0abfef":{
      "scriptId":"u35"},
    "4029ccce828343f9ace7fb2c3bc38389":{
      "scriptId":"u36"},
    "f48f3f9293664abeb886853faba7d3ac":{
      "scriptId":"u37"},
    "5460869bc0ef45bda9d7aee90a1b2519":{
      "scriptId":"u38"},
    "1580ddadddbd4235822b83096ca75ac2":{
      "scriptId":"u39"},
    "e7de2ea3ed904ddca4db1e5f5ab890cd":{
      "scriptId":"u40"},
    "93fa7b5010f14a8597aabf674873409b":{
      "scriptId":"u41"},
    "267949183c8e4bc6a76a5f68eb9e3c7d":{
      "scriptId":"u42"},
    "bb60322b8c03455ba5e34f45c86d7c1c":{
      "scriptId":"u43"},
    "a058c51c90f543b196e54e3df0c6db46":{
      "scriptId":"u44"},
    "2b31cf087ec94b2193c090e1dbb5bf17":{
      "scriptId":"u45"},
    "bcc7f82901ae4c1d9d2cdab660cc0f0c":{
      "scriptId":"u46"},
    "84f53204c3b14220afcc2a546ab7291e":{
      "scriptId":"u47"},
    "105bf40427a24448ac823ff5d60c4d9b":{
      "scriptId":"u48"},
    "3bf9841b23d840c8b8382e4b70c727cd":{
      "scriptId":"u49"},
    "ce6aa6e6fd99443ebb029cad3fe7e6fa":{
      "scriptId":"u50"},
    "23be619e8c5445bf98d355f0a5112002":{
      "scriptId":"u51"},
    "0b677b049bcf489f9f8b7d5e3836b256":{
      "scriptId":"u52"},
    "8bb0c57d86f34fb093bc5a981c9e1a12":{
      "scriptId":"u53"},
    "591f84e54c2b440eb16311e7be8aaa5d":{
      "scriptId":"u54"},
    "ba20a4c7da2c4d7da2880fea7cf3ea68":{
      "scriptId":"u55"},
    "31f4e919c25543c395805ee14272b722":{
      "scriptId":"u56"},
    "108c9184326941edb5c3a7b1e1cd4fc9":{
      "scriptId":"u57"},
    "4df123ca6437443e923a9ca0c05b00da":{
      "scriptId":"u58"},
    "e626c4ef23364b30adb167b5f8006dc4":{
      "scriptId":"u59"},
    "b6db923343604650aeabb3da5cbc9706":{
      "scriptId":"u60"},
    "a107dfe5c1f64241a181254683c9f5a4":{
      "scriptId":"u61"},
    "af3c0b35fcc546658db545805a44390a":{
      "scriptId":"u62"},
    "1ed0243533c94db39ae53e67b07c44aa":{
      "scriptId":"u63"},
    "0a9f28d4de734685aa4a175ce97b9fa9":{
      "scriptId":"u64"},
    "a31c8dcfeeb144089bfc7e5f8bf441d8":{
      "scriptId":"u65"},
    "81ef9b346cbe4e389d5bec700a58d0a7":{
      "scriptId":"u66"},
    "ab8d86740cb145268042df1d0d94b28b":{
      "scriptId":"u67"},
    "b5d2a6ee14a04d078ac38c5b00fc9665":{
      "scriptId":"u68"},
    "fdfaec880ba443f9a07c5a2717254501":{
      "scriptId":"u69"},
    "42036ac036544121b889db0dee928476":{
      "scriptId":"u70"},
    "ba21e85d96374c4eb987f80fd698f14f":{
      "scriptId":"u71"},
    "284d115c9d3b4d5ca6f96e9e384b3a21":{
      "scriptId":"u72"},
    "cea065e1d89b4d96a7cac1fda7ae5936":{
      "scriptId":"u73"},
    "53ebb1e803e8418c91541f337991a609":{
      "scriptId":"u74"},
    "beda9e50c937466a9f65f03c801a7209":{
      "scriptId":"u75"},
    "3db83cd007a841b489a3367473a2414f":{
      "scriptId":"u76"},
    "ee86e3a2132b40898ac5141d97197d02":{
      "scriptId":"u77"},
    "8f02b7ef713445199b448fbd038870f5":{
      "scriptId":"u78"},
    "089b4dd16e3348239746f7620ef1097e":{
      "scriptId":"u79"}}});