$axure.loadCurrentPage({
  "url":"meadmin_details_educ_entity_headerfoot.html",
  "generationDate":new Date(1396297420055.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d9142e82c08f40f2bac811de659e7779",
    "type":"Axure:Page",
    "name":"MeAdmin_Details_educ.entity_headerfoot",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkFrame",
                "description":"Open MeAdmin_Details_programme_flowchart in grid_frame_01",
                "linkType":"frame",
                "framesToTargets":[{
                    "framePath":["d76416108575457a9a016beed883d1f0"],
                    "target":{
                      "targetType":"page",
                      "url":"meadmin_details_programme_flowchart.html",
                      "includeVariables":true}}]},
{
                "action":"setFunction",
                "description":"Set is selected of ettan equal to &quot;true&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["d2e51ff8df0048109473d6c7a957f323"]},
{
                          "exprType":"stringLiteral",
                          "value":"true",
                          "stos":[]}]}]}}]}]}},
    "diagram":{
      "objects":[{
          "id":"1f7a5cc7e741468db04345844acbca4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "size":{
              "width":899,
              "height":608},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":2,
              "color":{
                "r":51,
                "g":51,
                "b":51,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11e9eb3ed82c45d29f5ee59d6555efe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "size":{
                  "width":899,
                  "height":608},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":2,
                  "color":{
                    "r":51,
                    "g":51,
                    "b":51,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u0.png"}},
{
          "id":"4fef6e6516c347f290f397f40d3c21fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFCECECE},
{
                  "color":0xFFCECECE}]},
            "size":{
              "width":900,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57f1a2d03a55468696f34383f8e24cd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFCECECE},
{
                      "color":0xFFCECECE}]},
                "size":{
                  "width":900,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u4.png"}},
{
          "id":"79c831d9a2ff4c38be8f6df8f1683225",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Fet', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":28,
              "y":6},
            "size":{
              "width":87,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da30f2e37aa74fb991504a8d4ddc040c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Fet', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":6},
                "size":{
                  "width":87,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56524483db3b45cd936c629b905c5db4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":6},
            "size":{
              "width":13,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f16012fa08840b9b8112f334227a032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":6},
                "size":{
                  "width":13,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u8.png"}},
{
          "id":"e075e77ef1df43fca37443a6fc0e8b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1EE},
            "location":{
              "x":1,
              "y":25},
            "size":{
              "width":897,
              "height":41},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e25e581a75542c6a879f206e95aa9fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1EE},
                "location":{
                  "x":1,
                  "y":25},
                "size":{
                  "width":897,
                  "height":41},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u8.png"}},
{
          "id":"43f6be4cf036422b8107843e2475f3bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Fet', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":97,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7c25a09c31643e3943ded7b7a923b1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Fet', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":97,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31bb0165514c48908162c7713ee418ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC5C5C5},
            "location":{
              "x":0,
              "y":571},
            "size":{
              "width":899,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b302365985c44e1c81577b15fd9ef33c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC5C5C5},
                "location":{
                  "x":0,
                  "y":571},
                "size":{
                  "width":899,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u2.png"}},
{
          "id":"caa3a129eda749e7893fd4902887aede",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF464646,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2}]},
            "location":{
              "x":823,
              "y":575},
            "size":{
              "width":65,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"003ff9a7ec6942c49b8d872978cba11c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF464646,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2}]},
                "location":{
                  "x":823,
                  "y":575},
                "size":{
                  "width":65,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u14.png"}},
{
          "id":"e06ff81c1e844859a7eaf78d615a30de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF464646,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2}]},
            "location":{
              "x":9,
              "y":575},
            "size":{
              "width":93,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99e20169403249beb1f23345a684bdcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF464646,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2}]},
                "location":{
                  "x":9,
                  "y":575},
                "size":{
                  "width":93,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u16.png"}},
{
          "id":"c9eaa682be584e14b44f1f9ac3fdac95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Fet', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":40,
              "y":48},
            "size":{
              "width":404,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"650d3de7e3404e93ba5709b0016a1db7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Fet', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":48},
                "size":{
                  "width":404,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68c2e15d67644c27b0de20228e989340",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":32},
            "size":{
              "width":27,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05e750e0dc3b4cdeb1eb757dc24ca622",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":32},
                "size":{
                  "width":27,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u20.png"}},
{
          "id":"d76416108575457a9a016beed883d1f0",
          "label":"grid_frame_01",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":899,
              "height":482}},
          "adaptiveStyles":{
}},
{
          "id":"a551bf2b8876403a8d683828ca238a89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFCECECE},
{
                  "color":0xFFCECECE}]},
            "location":{
              "x":0,
              "y":66},
            "size":{
              "width":900,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd9abfcbbdc94e709d9cbb268652b153",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFCECECE},
{
                      "color":0xFFCECECE}]},
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":900,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u23.png"}},
{
          "id":"f78b0ae94e174f4aafa10cfaf03612fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Fet', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":11,
              "y":72},
            "size":{
              "width":134,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3ce1a957c364eac946d198c935f8099",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Fet', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":72},
                "size":{
                  "width":134,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6207a8e7bb7640c787a0a920396562dd",
          "label":"first",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}},
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFB9BCC4},
            "location":{
              "x":637,
              "y":69},
            "size":{
              "width":130,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b3a35dfdd9b43a191fbd4508d01e925",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}},
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFB9BCC4},
                "location":{
                  "x":637,
                  "y":69},
                "size":{
                  "width":130,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"Open MeAdmin_Details_programme_structure in grid_frame_01",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["d76416108575457a9a016beed883d1f0"],
                          "target":{
                            "targetType":"page",
                            "url":"meadmin_details_programme_structure.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/first_u27.png",
            "selected~":"images/meadmin_details_educ_entity_headerfoot/first_u27_selected.png",
            "mouseOver~":"images/meadmin_details_educ_entity_headerfoot/first_u27_selected.png"}},
{
          "id":"5e6afbd052dd4b30920d5cca9a8b9f51",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":83},
            "size":{
              "width":899,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8B9BA8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/meadmin_details_educ_entity_headerfoot/u29_line.png"}},
{
          "id":"8c90ce6e50dc45eb8ccde00eb81885a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}},
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFB9BCC4},
            "location":{
              "x":543,
              "y":69},
            "size":{
              "width":99,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad45f8842fca4fcc8dc64342a647b22b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}},
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFB9BCC4},
                "location":{
                  "x":543,
                  "y":69},
                "size":{
                  "width":99,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"Open MeAdmin_Details_programme_Periods in grid_frame_01",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["d76416108575457a9a016beed883d1f0"],
                          "target":{
                            "targetType":"page",
                            "url":"meadmin_details_programme_periods.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u30.png",
            "selected~":"images/meadmin_details_educ_entity_headerfoot/u30_selected.png",
            "mouseOver~":"images/meadmin_details_educ_entity_headerfoot/u30_selected.png"}},
{
          "id":"d2e51ff8df0048109473d6c7a957f323",
          "label":"ettan",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}},
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFB9BCC4},
            "location":{
              "x":762,
              "y":69},
            "size":{
              "width":133,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fbc9ba1adf94cfab8cdec72bac8d287",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}},
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFB9BCC4},
                "location":{
                  "x":762,
                  "y":69},
                "size":{
                  "width":133,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"Open MeAdmin_Details_programme_flowchart in grid_frame_01",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["d76416108575457a9a016beed883d1f0"],
                          "target":{
                            "targetType":"page",
                            "url":"meadmin_details_programme_flowchart.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/ettan_u32.png",
            "selected~":"images/meadmin_details_educ_entity_headerfoot/ettan_u32_selected.png",
            "mouseOver~":"images/meadmin_details_educ_entity_headerfoot/ettan_u32_selected.png"}},
{
          "id":"5c361a099a214fc0b23f200217d65c37",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"08a17894b6834e76b34f5da7ed0ce844"},
{
          "id":"0979e64ecdb442d5a31ca5c7098c2265",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Fet', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFBD22},
            "location":{
              "x":177,
              "y":27},
            "size":{
              "width":372,
              "height":19},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2675d947bdd44621acb8d5d34e4271f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Fet', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFBD22},
                "location":{
                  "x":177,
                  "y":27},
                "size":{
                  "width":372,
                  "height":19},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u73.png"}}]}},
  "masters":{
    "08a17894b6834e76b34f5da7ed0ce844":{
      "packageId":"08a17894b6834e76b34f5da7ed0ce844",
      "type":"Axure:Master",
      "name":"Programme_list_action",
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5ba718831c5c48eb97273425037aa9d2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF464646,
                "opacity":1},
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFCCCCCC},
{
                    "color":0xFFCCCCCC},
{
                    "color":0xFFF2F2F2},
{
                    "color":0xFFF2F2F2}]},
              "location":{
                "x":831,
                "y":29},
              "size":{
                "width":58,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF666666},
              "cornerRadiusTopLeft":"1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bee026f8d9294b0983d85e50b83da7e4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF464646,
                    "opacity":1},
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFCCCCCC},
{
                        "color":0xFFCCCCCC},
{
                        "color":0xFFF2F2F2},
{
                        "color":0xFFF2F2F2}]},
                  "location":{
                    "x":831,
                    "y":29},
                  "size":{
                    "width":58,
                    "height":16},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "cornerRadiusTopLeft":"1"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle RCmenu_001",
                        "objectsToFades":[{
                            "objectPath":["3af87b29788e4583831dbf8c7b867934"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/meadmin_details_educ_entity_headerfoot/u35.png"}},
{
            "id":"23f5391fd44f40d086b3e4d3bf498213",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":838,
                "y":34},
              "size":{
                "width":7,
                "height":7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b4ac22caad5545159dd52c3ca41b9005",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":838,
                    "y":34},
                  "size":{
                    "width":7,
                    "height":7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle RCmenu_001",
                        "objectsToFades":[{
                            "objectPath":["3af87b29788e4583831dbf8c7b867934"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/meadmin_details_educ_entity_headerfoot/u37.png"}},
{
            "id":"3af87b29788e4583831dbf8c7b867934",
            "label":"RCmenu_001",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":false,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFEEEEEE},
              "location":{
                "x":703,
                "y":29},
              "size":{
                "width":101,
                "height":165},
              "visible":false},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"41684aead77d481b9e5c4754079915b2",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":101,
                    "height":165}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"dcf0b5d6278243959965856103125052",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":101,
                        "height":20},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"be2ea352f2fb4aabb89720080b7ea86d",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":101,
                            "height":20},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"ac6fedd09671407f9faf836bcca4e496",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":102},
                      "size":{
                        "width":101,
                        "height":21},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"ede6b39bf0f24eefbd61e333483f50c4",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":102},
                          "size":{
                            "width":101,
                            "height":21},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"db5545c29dee47239cbf97977d8e8dea",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":60},
                      "size":{
                        "width":101,
                        "height":21},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"32dfc7daaafb43bf931e5e3564266a7d",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":60},
                          "size":{
                            "width":101,
                            "height":21},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"e2c58cfef8fa4dafb3401f74dafc7a3f",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":81},
                      "size":{
                        "width":101,
                        "height":21},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b76cc261a65f4010ab8d62e6cf908497",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":81},
                          "size":{
                            "width":101,
                            "height":21},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"76ea5e9654e04ac19209e8b08e6c297d",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":123},
                      "size":{
                        "width":101,
                        "height":21},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"082612a557c1447689c601bf572cde48",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":123},
                          "size":{
                            "width":101,
                            "height":21},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1d65829415744cd58543fb5efec64831",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":144},
                      "size":{
                        "width":101,
                        "height":21},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d54e84ff58e344e9a5baddb21f802335",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":144},
                          "size":{
                            "width":101,
                            "height":21},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"21cee47a2ab14b6f98f10b63af676db4",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":20},
                      "size":{
                        "width":101,
                        "height":20},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"dbe44a5ec9934fb5b350f9b5b9425d0f",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":20},
                          "size":{
                            "width":101,
                            "height":20},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"206fab9290ba4f129f7a7d4a93b0fc2b",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":101,
                        "height":20},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"63273b8874794832acf56c1e53ae4909",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":101,
                            "height":20},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]},
{
                "id":"4acd60b31a2843ebb6a3d91e21597f20",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFEEEEEE},
                  "location":{
                    "x":101,
                    "y":144},
                  "size":{
                    "width":59,
                    "height":40},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2c3095bc8e724e859a6580fbc21f34a4",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":59,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3a144aca174f42eba3e6a4533f399565",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":59,
                            "height":20},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"9aaaa79066fb4aa8875676b353fda761",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"10px",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "lineSpacing":"6px",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":59,
                                "height":20},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFCCCCCC}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"1497ff6534a043419f1d4733cd3291a3",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":20},
                          "size":{
                            "width":59,
                            "height":20},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"1d8e6a4b78154e3b87de356a64866e7c",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"10px",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "lineSpacing":"6px",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":20},
                              "size":{
                                "width":59,
                                "height":20},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFCCCCCC}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}}]}],
                "parentCellId":"1d65829415744cd58543fb5efec64831"},
{
                "id":"c68477fae2a341eda0ede5e98e58075b",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFEEEEEE},
                  "location":{
                    "x":101,
                    "y":123},
                  "size":{
                    "width":100,
                    "height":80},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"e355eac3ad49459d9c5bcde10e484646",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":100,
                        "height":80}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"dc0e2059a05e411ba808d2ababeb3201",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"f9e4e65cf1c64303bbe1d73f04d7dda5",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"10px",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "lineSpacing":"6px",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFCCCCCC}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"38d99630707e4ed583b452250efe322c",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":20},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"b64f2fddc373420ba8e6f9863cb32212",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"10px",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "lineSpacing":"6px",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":20},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFCCCCCC}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"b963f1ffc5f34e2784bfb72ad6e3e160",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"33e508553296494f98a9135dfbbc6c4c",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"10px",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "lineSpacing":"6px",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":40},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFCCCCCC}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"262ccc1d409046babf36251ee666463f",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":60},
                          "size":{
                            "width":100,
                            "height":20},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"d793522d5c224e288766e4362ee24b6d",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"10px",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "lineSpacing":"6px",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":60},
                              "size":{
                                "width":100,
                                "height":20},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFCCCCCC}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}}]}],
                "parentCellId":"76ea5e9654e04ac19209e8b08e6c297d"}]}]}}},
  "objectPaths":{
    "1f7a5cc7e741468db04345844acbca4c":{
      "scriptId":"u0"},
    "11e9eb3ed82c45d29f5ee59d6555efe1":{
      "scriptId":"u1"},
    "4fef6e6516c347f290f397f40d3c21fa":{
      "scriptId":"u2"},
    "57f1a2d03a55468696f34383f8e24cd4":{
      "scriptId":"u3"},
    "79c831d9a2ff4c38be8f6df8f1683225":{
      "scriptId":"u4"},
    "da30f2e37aa74fb991504a8d4ddc040c":{
      "scriptId":"u5"},
    "56524483db3b45cd936c629b905c5db4":{
      "scriptId":"u6"},
    "2f16012fa08840b9b8112f334227a032":{
      "scriptId":"u7"},
    "e075e77ef1df43fca37443a6fc0e8b2a":{
      "scriptId":"u8"},
    "8e25e581a75542c6a879f206e95aa9fc":{
      "scriptId":"u9"},
    "43f6be4cf036422b8107843e2475f3bf":{
      "scriptId":"u10"},
    "a7c25a09c31643e3943ded7b7a923b1f":{
      "scriptId":"u11"},
    "31bb0165514c48908162c7713ee418ef":{
      "scriptId":"u12"},
    "b302365985c44e1c81577b15fd9ef33c":{
      "scriptId":"u13"},
    "caa3a129eda749e7893fd4902887aede":{
      "scriptId":"u14"},
    "003ff9a7ec6942c49b8d872978cba11c":{
      "scriptId":"u15"},
    "e06ff81c1e844859a7eaf78d615a30de":{
      "scriptId":"u16"},
    "99e20169403249beb1f23345a684bdcb":{
      "scriptId":"u17"},
    "c9eaa682be584e14b44f1f9ac3fdac95":{
      "scriptId":"u18"},
    "650d3de7e3404e93ba5709b0016a1db7":{
      "scriptId":"u19"},
    "68c2e15d67644c27b0de20228e989340":{
      "scriptId":"u20"},
    "05e750e0dc3b4cdeb1eb757dc24ca622":{
      "scriptId":"u21"},
    "d76416108575457a9a016beed883d1f0":{
      "scriptId":"u22"},
    "a551bf2b8876403a8d683828ca238a89":{
      "scriptId":"u23"},
    "dd9abfcbbdc94e709d9cbb268652b153":{
      "scriptId":"u24"},
    "f78b0ae94e174f4aafa10cfaf03612fe":{
      "scriptId":"u25"},
    "d3ce1a957c364eac946d198c935f8099":{
      "scriptId":"u26"},
    "6207a8e7bb7640c787a0a920396562dd":{
      "scriptId":"u27"},
    "5b3a35dfdd9b43a191fbd4508d01e925":{
      "scriptId":"u28"},
    "5e6afbd052dd4b30920d5cca9a8b9f51":{
      "scriptId":"u29"},
    "8c90ce6e50dc45eb8ccde00eb81885a9":{
      "scriptId":"u30"},
    "ad45f8842fca4fcc8dc64342a647b22b":{
      "scriptId":"u31"},
    "d2e51ff8df0048109473d6c7a957f323":{
      "scriptId":"u32"},
    "0fbc9ba1adf94cfab8cdec72bac8d287":{
      "scriptId":"u33"},
    "5c361a099a214fc0b23f200217d65c37":{
      "scriptId":"u34",
      "5ba718831c5c48eb97273425037aa9d2":{
        "scriptId":"u35"},
      "bee026f8d9294b0983d85e50b83da7e4":{
        "scriptId":"u36"},
      "23f5391fd44f40d086b3e4d3bf498213":{
        "scriptId":"u37"},
      "b4ac22caad5545159dd52c3ca41b9005":{
        "scriptId":"u38"},
      "3af87b29788e4583831dbf8c7b867934":{
        "scriptId":"u39"},
      "41684aead77d481b9e5c4754079915b2":{
        "scriptId":"u40"},
      "dcf0b5d6278243959965856103125052":{
        "scriptId":"u41"},
      "be2ea352f2fb4aabb89720080b7ea86d":{
        "scriptId":"u42"},
      "21cee47a2ab14b6f98f10b63af676db4":{
        "scriptId":"u43"},
      "dbe44a5ec9934fb5b350f9b5b9425d0f":{
        "scriptId":"u44"},
      "206fab9290ba4f129f7a7d4a93b0fc2b":{
        "scriptId":"u45"},
      "63273b8874794832acf56c1e53ae4909":{
        "scriptId":"u46"},
      "db5545c29dee47239cbf97977d8e8dea":{
        "scriptId":"u47"},
      "32dfc7daaafb43bf931e5e3564266a7d":{
        "scriptId":"u48"},
      "e2c58cfef8fa4dafb3401f74dafc7a3f":{
        "scriptId":"u49"},
      "b76cc261a65f4010ab8d62e6cf908497":{
        "scriptId":"u50"},
      "ac6fedd09671407f9faf836bcca4e496":{
        "scriptId":"u51"},
      "ede6b39bf0f24eefbd61e333483f50c4":{
        "scriptId":"u52"},
      "76ea5e9654e04ac19209e8b08e6c297d":{
        "scriptId":"u53"},
      "082612a557c1447689c601bf572cde48":{
        "scriptId":"u54"},
      "1d65829415744cd58543fb5efec64831":{
        "scriptId":"u55"},
      "d54e84ff58e344e9a5baddb21f802335":{
        "scriptId":"u56"},
      "4acd60b31a2843ebb6a3d91e21597f20":{
        "scriptId":"u57"},
      "2c3095bc8e724e859a6580fbc21f34a4":{
        "scriptId":"u58"},
      "3a144aca174f42eba3e6a4533f399565":{
        "scriptId":"u59"},
      "9aaaa79066fb4aa8875676b353fda761":{
        "scriptId":"u60"},
      "1497ff6534a043419f1d4733cd3291a3":{
        "scriptId":"u61"},
      "1d8e6a4b78154e3b87de356a64866e7c":{
        "scriptId":"u62"},
      "c68477fae2a341eda0ede5e98e58075b":{
        "scriptId":"u63"},
      "e355eac3ad49459d9c5bcde10e484646":{
        "scriptId":"u64"},
      "dc0e2059a05e411ba808d2ababeb3201":{
        "scriptId":"u65"},
      "f9e4e65cf1c64303bbe1d73f04d7dda5":{
        "scriptId":"u66"},
      "38d99630707e4ed583b452250efe322c":{
        "scriptId":"u67"},
      "b64f2fddc373420ba8e6f9863cb32212":{
        "scriptId":"u68"},
      "b963f1ffc5f34e2784bfb72ad6e3e160":{
        "scriptId":"u69"},
      "33e508553296494f98a9135dfbbc6c4c":{
        "scriptId":"u70"},
      "262ccc1d409046babf36251ee666463f":{
        "scriptId":"u71"},
      "d793522d5c224e288766e4362ee24b6d":{
        "scriptId":"u72"}},
    "0979e64ecdb442d5a31ca5c7098c2265":{
      "scriptId":"u73"},
    "2675d947bdd44621acb8d5d34e4271f2":{
      "scriptId":"u74"}}});