/*
 GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 @author  Jan Odvarko, http://odvarko.cz
 @created 2008-06-15
 @updated 2010-01-23
 @link    http://jscolor.com
*/
var jscolor={dir:"",bindClass:"color",binding:true,preloading:true,install:function(){jscolor.addEvent(window,"load",jscolor.init)},init:function(){jscolor.binding&&jscolor.bind();jscolor.preloading&&jscolor.preload()},getDir:function(){if(!jscolor.dir){var d=jscolor.detectDir();jscolor.dir=d!==false?d:"jscolor/"}return jscolor.dir},detectDir:function(){for(var d=location.href,g=document.getElementsByTagName("base"),c=0;c<g.length;c+=1)if(g[c].href)d=g[c].href;g=document.getElementsByTagName("script");
for(c=0;c<g.length;c+=1)if(g[c].src&&/(^|\/)jscolor\.js([?#].*)?$/i.test(g[c].src)){d=(new jscolor.URI(g[c].src)).toAbsolute(d);d.path=d.path.replace(/[^\/]+$/,"");d.query=null;d.fragment=null;return d.toString()}return false},bind:function(){for(var d=RegExp("(^|\\s)("+jscolor.bindClass+")\\s*(\\{[^}]*\\})?","i"),g=document.getElementsByTagName("input"),c=0;c<g.length;c+=1){var j;if(!g[c].color&&g[c].className&&(j=g[c].className.match(d))){if(j[3])try{eval("prop="+j[3])}catch(u){}g[c].color=new jscolor.color(g[c],
{})}}},preload:function(){for(var d in jscolor.imgRequire)jscolor.imgRequire.hasOwnProperty(d)&&jscolor.loadImage(d)},images:{pad:[181,101],sld:[16,101],cross:[15,15],arrow:[7,11]},TitleBox:{height:40},CommandBox:{height:22},ColorExport:{code:"ffffff",backgroundColor:"#ffffff",color:"#000000"},imgRequire:{},imgLoaded:{},requireImage:function(d){jscolor.imgRequire[d]=true},loadImage:function(d){if(!jscolor.imgLoaded[d]){jscolor.imgLoaded[d]=new Image;jscolor.imgLoaded[d].src=jscolor.getDir()+d}},fetchElement:function(d){return typeof d===
"string"?document.getElementById(d):d},addEvent:function(d,g,c){if(d.addEventListener)d.addEventListener(g,c,false);else d.attachEvent&&d.attachEvent("on"+g,c)},fireEvent:function(d,g){if(d)if(document.createEventObject){var c=document.createEventObject();d.fireEvent("on"+g,c)}else if(document.createEvent){c=document.createEvent("HTMLEvents");c.initEvent(g,true,true);d.dispatchEvent(c)}else d["on"+g]&&d["on"+g]()},getElementPos:function(d){var g=d;d=d;var c=0,j=0;if(g.offsetParent){do{c+=g.offsetLeft;
j+=g.offsetTop}while(g=g.offsetParent)}for(;(d=d.parentNode)&&d.nodeName.toUpperCase()!=="BODY";){c-=d.scrollLeft;j-=d.scrollTop}return[c,j]},getElementSize:function(d){return[d.offsetWidth,d.offsetHeight]},getMousePos:function(d){if(!d)d=window.event;if(typeof d.pageX==="number")return[d.pageX,d.pageY];else if(typeof d.clientX==="number")return[d.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,d.clientY+document.body.scrollTop+document.documentElement.scrollTop]},getViewPos:function(){return typeof window.pageYOffset===
"number"?[window.pageXOffset,window.pageYOffset]:document.body&&(document.body.scrollLeft||document.body.scrollTop)?[document.body.scrollLeft,document.body.scrollTop]:document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[0,0]},getViewSize:function(){return typeof window.innerWidth==="number"?[window.innerWidth,window.innerHeight]:document.body&&(document.body.clientWidth||document.body.clientHeight)?
[document.body.clientWidth,document.body.clientHeight]:document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?[document.documentElement.clientWidth,document.documentElement.clientHeight]:[0,0]},URI:function(d){function g(c){for(var j="";c;)if(c.substr(0,3)==="../"||c.substr(0,2)==="./")c=c.replace(/^\.+/,"").substr(1);else if(c.substr(0,3)==="/./"||c==="/.")c="/"+c.substr(3);else if(c.substr(0,4)==="/../"||c==="/.."){c="/"+c.substr(4);j=j.replace(/\/?[^\/]*$/,
"")}else if(c==="."||c==="..")c="";else{var u=c.match(/^\/?[^\/]*/)[0];c=c.substr(u.length);j+=u}return j}this.authority=this.scheme=null;this.path="";this.fragment=this.query=null;this.parse=function(c){c=c.match(/^(([A-Za-z][0-9A-Za-z+.-]*)(:))?((\/\/)([^\/?#]*))?([^?#]*)((\?)([^#]*))?((#)(.*))?/);this.scheme=c[3]?c[2]:null;this.authority=c[5]?c[6]:null;this.path=c[7];this.query=c[9]?c[10]:null;this.fragment=c[12]?c[13]:null;return this};this.toString=function(){var c="";if(this.scheme!==null)c=
c+this.scheme+":";if(this.authority!==null)c=c+"//"+this.authority;if(this.path!==null)c+=this.path;if(this.query!==null)c=c+"?"+this.query;if(this.fragment!==null)c=c+"#"+this.fragment;return c};this.toAbsolute=function(c){c=new jscolor.URI(c);var j=new jscolor.URI;if(c.scheme===null)return false;if(this.scheme!==null&&this.scheme.toLowerCase()===c.scheme.toLowerCase())this.scheme=null;if(this.scheme!==null){j.scheme=this.scheme;j.authority=this.authority;j.path=g(this.path);j.query=this.query}else{if(this.authority!==
null){j.authority=this.authority;j.path=g(this.path);j.query=this.query}else{if(this.path===""){j.path=c.path;j.query=this.query!==null?this.query:c.query}else{if(this.path.substr(0,1)==="/")j.path=g(this.path);else{j.path=c.authority!==null&&c.path===""?"/"+this.path:c.path.replace(/[^\/]+$/,"")+this.path;j.path=g(j.path)}j.query=this.query}j.authority=c.authority}j.scheme=c.scheme}j.fragment=this.fragment;return j};d&&this.parse(d)},color:function(d,g){function c(b,e,a){if(b===null)return[a,a,a];
var i=Math.floor(b),l=a*(1-e);b=a*(1-e*(i%2?b-i:1-(b-i)));switch(i){case 6:case 0:return[a,b,l];case 1:return[b,a,l];case 2:return[l,a,b];case 3:return[l,b,a];case 4:return[b,l,a];case 5:return[a,l,b]}}function j(){delete jscolor.picker.owner;document.getElementsByTagName("body")[0].removeChild(jscolor.picker.boxB)}function u(b,e){if(!jscolor.picker){jscolor.picker={box:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),
padM:document.createElement("div"),sld:document.createElement("div"),sldB:document.createElement("div"),sldM:document.createElement("div"),TitleBox:document.createElement("div"),boxCmd:document.createElement("div")};for(var a=0;a<jscolor.images.sld[1];a+=4){var i=document.createElement("div");i.style.height="4px";i.style.fontSize="1px";i.style.lineHeight="0";jscolor.picker.sld.appendChild(i)}jscolor.picker.sldB.appendChild(jscolor.picker.sld);jscolor.picker.box.appendChild(jscolor.picker.TitleBox);
jscolor.picker.box.appendChild(jscolor.picker.sldB);jscolor.picker.box.appendChild(jscolor.picker.sldM);jscolor.picker.padB.appendChild(jscolor.picker.pad);jscolor.picker.box.appendChild(jscolor.picker.padB);jscolor.picker.box.appendChild(jscolor.picker.padM);jscolor.picker.box.appendChild(jscolor.picker.boxCmd);jscolor.picker.boxB.appendChild(jscolor.picker.box)}a=jscolor.picker;x=[b+f.pickerBorder+f.pickerFace+f.pickerInset,e+f.pickerBorder+f.pickerFace+f.pickerInset];a.box.onmouseup=a.box.onmouseout=
function(){d.focus()};a.box.onmousedown=function(){v=true};a.box.onmousemove=function(s){y&&E(s);z&&F(s)};a.padM.onmouseup=a.padM.onmouseout=function(){if(y){y=false;jscolor.fireEvent(m,"change")}};a.padM.onmousedown=function(s){y=true;E(s)};a.sldM.onmouseup=a.sldM.onmouseout=function(){if(z){z=false;jscolor.fireEvent(m,"change")}};a.sldM.onmousedown=function(s){z=true;F(s)};a.box.style.width=4*f.pickerInset+2*f.pickerFace+jscolor.images.pad[0]+2*jscolor.images.arrow[0]+jscolor.images.sld[0]+"px";
a.box.style.height=2*f.pickerInset+2*f.pickerFace+jscolor.images.pad[1]+jscolor.TitleBox.height+jscolor.CommandBox.height+"px";a.boxB.style.position="absolute";a.boxB.style.clear="both";a.boxB.style.left=b+"px";a.boxB.style.top=e+"px";a.boxB.style.zIndex=f.pickerZIndex;a.boxB.style.border=f.pickerBorder+"px solid";a.boxB.style.borderColor=f.pickerBorderColor;a.boxB.style.background=f.pickerFaceColor;a.pad.style.width=jscolor.images.pad[0]+"px";for(a.pad.style.height=jscolor.images.pad[1]+"px";a.TitleBox.firstChild;)a.TitleBox.removeChild(a.TitleBox.firstChild);
a.TitleBox.style.position="absolute";a.TitleBox.style.left=f.pickerFace+"px";a.TitleBox.style.top=f.pickerFace+"px";i=document.createElement("div");i.setAttribute("id","lblTitle");i.innerHTML="Colorpicker";a.TitleBox.appendChild(i);var l=document.createElement("div");l.style.whiteSpace="nowrap";var k=document.createElement("div");k.setAttribute("id","divColorCode");k.style.cssText="float:left;display:inline;";var h=document.createElement("div");h.setAttribute("id","color-box");f.fromString(m.value);
jscolor.ColorExport.code="#"+f.toString();jscolor.ColorExport.backgroundColor=jscolor.ColorExport.code;jscolor.ColorExport.color=0.213*f.rgb[0]+0.715*f.rgb[1]+0.072*f.rgb[2]<0.5?"#FFF":"#000";k.innerHTML=jscolor.ColorExport.code;h.style.backgroundColor=jscolor.ColorExport.code;var o=document.createElement("div");if(window.navigator.userAgent.indexOf("MSIE")>=0){i=window.navigator.userAgent.substr(window.navigator.userAgent.indexOf("MSIE")+5,3);i>=6&&i<8?o.setAttribute("className","clear"):o.setAttribute("class",
"clear")}else o.setAttribute("class","clear");l.appendChild(h);l.appendChild(k);l.appendChild(o);a.TitleBox.appendChild(l);a.padB.style.position="absolute";a.padB.style.left=f.pickerFace+"px";a.padB.style.top=f.pickerFace+jscolor.TitleBox.height+"px";a.padB.style.border=f.pickerInset+"px solid";a.padB.style.borderColor=f.pickerInsetColor;a.padM.style.position="absolute";a.padM.style.left="0";a.padM.style.top=jscolor.TitleBox.height+"px";a.padM.style.width=f.pickerFace+2*f.pickerInset+jscolor.images.pad[0]+
jscolor.images.arrow[0]+"px";a.padM.style.height=parseInt(a.box.style.height)-jscolor.TitleBox.height-jscolor.CommandBox.height+"px";a.padM.style.cursor="crosshair";a.sld.style.overflow="hidden";a.sld.style.width=jscolor.images.sld[0]+"px";a.sld.style.height=jscolor.images.sld[1]+"px";a.sldB.style.position="absolute";a.sldB.style.right=f.pickerFace+"px";a.sldB.style.top=f.pickerFace+jscolor.TitleBox.height+"px";a.sldB.style.border=f.pickerInset+"px solid";a.sldB.style.borderColor=f.pickerInsetColor;
a.sldM.style.position="absolute";a.sldM.style.right="0";a.sldM.style.top=jscolor.TitleBox.height+"px";a.sldM.style.width=jscolor.images.sld[0]+jscolor.images.arrow[0]+f.pickerFace+2*f.pickerInset+"px";a.sldM.style.height=parseInt(a.box.style.height)-jscolor.TitleBox.height-jscolor.CommandBox.height+"px";try{a.sldM.style.cursor="pointer"}catch(p){a.sldM.style.cursor="hand"}switch(r){case 0:var n="hs.png";break;case 1:n="hv.png"}a.padM.style.background="url('"+jscolor.getDir()+"cross.gif') no-repeat";
a.sldM.style.background="url('"+jscolor.getDir()+"arrow.gif') no-repeat";for(a.pad.style.background="url('"+jscolor.getDir()+n+"') 0 0 no-repeat";a.boxCmd.firstChild;)a.boxCmd.removeChild(a.boxCmd.firstChild);a.boxCmd.style.position="absolute";a.boxCmd.style.left=f.pickerFace+"px";a.boxCmd.style.top=2*f.pickerFace+parseInt(a.pad.style.height)+jscolor.TitleBox.height+"px";a.boxCmd.style.zIndex=f.pickerZIndex;n=document.createElement("a");n.setAttribute("id","btnOK");navigator.userAgent.toLowerCase();
i=0;if(window.navigator.userAgent.indexOf("MSIE")>=0){i=window.navigator.userAgent.substr(window.navigator.userAgent.indexOf("MSIE")+5,3);i>=6&&i<8?n.setAttribute("className","button"):n.setAttribute("class","button")}else n.setAttribute("class","button");n.innerHTML="Apply";jscolor.addEvent(n,"click",function(){m.value=jscolor.ColorExport.code;q.style.backgroundColor=jscolor.ColorExport.backgroundColor;q.style.color=jscolor.ColorExport.color;j();m.blur()});a.boxCmd.appendChild(n);n=document.createElement("a");
n.setAttribute("id","btnCancel");if(window.navigator.userAgent.indexOf("MSIE")>=0){i=window.navigator.userAgent.substr(window.navigator.userAgent.indexOf("MSIE")+5,3);i>=6&&i<=7?n.setAttribute("className","button"):n.setAttribute("class","button")}else n.setAttribute("class","button");n.style.margin="0 0 0 4px";n.innerHTML="Cancel";jscolor.addEvent(n,"click",function(){j();m.blur()});a.boxCmd.appendChild(n);G();H();jscolor.picker.owner=f;document.getElementsByTagName("body")[0].appendChild(a.boxB)}
function G(){switch(r){case 0:var b=1;break;case 1:b=2}jscolor.picker.padM.style.backgroundPosition=f.pickerFace+f.pickerInset+Math.round(f.hsv[0]/6*(jscolor.images.pad[0]-1))-Math.floor(jscolor.images.cross[0]/2)+"px "+(f.pickerFace+f.pickerInset+Math.round((1-f.hsv[b])*(jscolor.images.pad[1]-1))-Math.floor(jscolor.images.cross[1]/2))+"px";b=jscolor.picker.sld.childNodes;switch(r){case 0:for(var e=c(f.hsv[0],f.hsv[1],1),a=0;a<b.length;a+=1)b[a].style.backgroundColor="rgb("+e[0]*(1-a/b.length)*100+
"%,"+e[1]*(1-a/b.length)*100+"%,"+e[2]*(1-a/b.length)*100+"%)";break;case 1:var i,l=[f.hsv[2],0,0];a=Math.floor(f.hsv[0]);var k=a%2?f.hsv[0]-a:1-(f.hsv[0]-a);switch(a){case 6:case 0:e=[0,1,2];break;case 1:e=[1,0,2];break;case 2:e=[2,0,1];break;case 3:e=[2,1,0];break;case 4:e=[1,2,0];break;case 5:e=[0,2,1]}for(a=0;a<b.length;a+=1){i=1-1/(b.length-1)*a;l[1]=l[0]*(1-i*k);l[2]=l[0]*(1-i);b[a].style.backgroundColor="rgb("+l[e[0]]*100+"%,"+l[e[1]]*100+"%,"+l[e[2]]*100+"%)"}}}function H(){switch(r){case 0:var b=
2;break;case 1:b=1}jscolor.picker.sldM.style.backgroundPosition="0 "+(f.pickerFace+f.pickerInset+Math.round((1-f.hsv[b])*(jscolor.images.sld[1]-1))-Math.floor(jscolor.images.arrow[1]/2))+"px"}function A(){return jscolor.picker&&jscolor.picker.owner===f}function I(){m!==d&&f.importColor()}function E(b){var e=jscolor.getMousePos(b);b=e[0]-x[0];e=e[1]-x[1]-jscolor.TitleBox.height;switch(r){case 0:f.fromHSV(b*(6/(jscolor.images.pad[0]-1)),1-e/(jscolor.images.pad[1]-1),null,B);break;case 1:f.fromHSV(b*
(6/(jscolor.images.pad[0]-1)),null,1-e/(jscolor.images.pad[1]-1),B)}}function F(b){b=jscolor.getMousePos(b)[1]-x[1]-jscolor.TitleBox.height;switch(r){case 0:f.fromHSV(null,null,1-b/(jscolor.images.sld[1]-1),C);break;case 1:f.fromHSV(null,1-b/(jscolor.images.sld[1]-1),null,C)}}this.caps=this.hash=this.adjust=this.required=true;this.styleElement=this.valueElement=d;this.hsv=[0,0,1];this.rgb=[1,1,1];this.pickerOnfocus=true;this.pickerMode="HSV";this.pickerPosition="bottom";this.pickerFace=10;this.pickerFaceColor=
"ThreeDFace";this.pickerBorder=1;this.pickerBorderColor="ThreeDHighlight ThreeDShadow ThreeDShadow ThreeDHighlight";this.pickerInset=1;this.pickerInsetColor="ThreeDShadow ThreeDHighlight ThreeDHighlight ThreeDShadow";this.pickerZIndex=1E4;for(var t in g)if(g.hasOwnProperty(t))this[t]=g[t];this.hidePicker=function(){A()&&j()};this.showPicker=function(){if(!A()){var b=jscolor.getElementPos(d),e=jscolor.getElementSize(d),a=jscolor.getViewPos(),i=jscolor.getViewSize(),l=[2*this.pickerBorder+4*this.pickerInset+
2*this.pickerFace+jscolor.images.pad[0]+2*jscolor.images.arrow[0]+jscolor.images.sld[0],2*this.pickerBorder+2*this.pickerInset+2*this.pickerFace+jscolor.images.pad[1]],k,h,o;switch(this.pickerPosition.toLowerCase()){case "left":k=1;h=0;o=-1;break;case "right":k=1;h=0;o=1;break;case "top":k=0;h=1;o=-1;break;default:k=0;o=h=1}var p=(e[h]+l[h])/2;b=[-a[k]+b[k]+l[k]>i[k]?-a[k]+b[k]+e[k]/2>i[k]/2&&b[k]+e[k]-l[k]>=0?b[k]+e[k]-l[k]:b[k]:b[k],-a[h]+b[h]+e[h]+l[h]-p+p*o>i[h]?-a[h]+b[h]+e[h]/2>i[h]/2&&b[h]+
e[h]-p-p*o>=0?b[h]+e[h]-p-p*o:b[h]+e[h]-p+p*o:b[h]+e[h]-p+p*o>=0?b[h]+e[h]-p+p*o:b[h]+e[h]-p-p*o];u(b[k],b[h])}};this.importColor=function(){if(m)if(this.adjust)if(!this.required&&/^\s*$/.test(m.value)){m.value="";q.style.backgroundColor=q.jscStyle.backgroundColor;q.style.color=q.jscStyle.color;this.exportColor(w|D)}else this.fromString(m.value)||this.exportColor();else{if(!this.fromString(m.value,w)){q.style.backgroundColor=q.jscStyle.backgroundColor;q.style.color=q.jscStyle.color;this.exportColor(w|
D)}}else this.exportColor()};this.exportColor=function(b){var e=document.getElementById("divColorCode");if(!(b&w)&&m){var a=this.toString();if(this.caps)a=a.toUpperCase();if(this.hash)a="#"+a;jscolor.ColorExport.code=a;if(e!=null)e.innerHTML=a}if(!(b&D)&&q){jscolor.ColorExport.code="#"+this.toString();jscolor.ColorExport.backgroundColor="#"+this.toString();jscolor.ColorExport.color=0.213*this.rgb[0]+0.715*this.rgb[1]+0.072*this.rgb[2]<0.5?"#FFF":"#000";jscolor.ColorExport.code="#"+this;a=document.getElementById("color-box");
if(a!=null)a.style.backgroundColor=jscolor.ColorExport.backgroundColor;if(e!=null)e.innerHTML=jscolor.ColorExport.code}!(b&C)&&A()&&G();!(b&B)&&A()&&H()};this.fromHSV=function(b,e,a,i){b<0&&(b=0)||b>6&&(b=6);e<0&&(e=0)||e>1&&(e=1);a<0&&(a=0)||a>1&&(a=1);this.rgb=c(b===null?this.hsv[0]:this.hsv[0]=b,e===null?this.hsv[1]:this.hsv[1]=e,a===null?this.hsv[2]:this.hsv[2]=a);this.exportColor(i)};this.fromRGB=function(b,e,a,i){b<0&&(b=0)||b>1&&(b=1);e<0&&(e=0)||e>1&&(e=1);a<0&&(a=0)||a>1&&(a=1);b=b===null?
this.rgb[0]:this.rgb[0]=b;e=e===null?this.rgb[1]:this.rgb[1]=e;var l=a===null?this.rgb[2]:this.rgb[2]=a,k=Math.min(Math.min(b,e),l);a=Math.max(Math.max(b,e),l);var h=a-k;if(h===0)b=[null,0,a];else{b=b===k?3+(l-e)/h:e===k?5+(b-l)/h:1+(e-b)/h;b=[b===6?0:b,h/a,a]}if(b[0]!==null)this.hsv[0]=b[0];if(b[2]!==0)this.hsv[1]=b[1];this.hsv[2]=b[2];this.exportColor(i)};this.fromString=function(b,e){var a=b.match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i);if(a){a[1].length===6?this.fromRGB(parseInt(a[1].substr(0,
2),16)/255,parseInt(a[1].substr(2,2),16)/255,parseInt(a[1].substr(4,2),16)/255,e):this.fromRGB(parseInt(a[1].charAt(0)+a[1].charAt(0),16)/255,parseInt(a[1].charAt(1)+a[1].charAt(1),16)/255,parseInt(a[1].charAt(2)+a[1].charAt(2),16)/255,e);return true}else return false};this.toString=function(){return(256|Math.round(255*this.rgb[0])).toString(16).substr(1)+(256|Math.round(255*this.rgb[1])).toString(16).substr(1)+(256|Math.round(255*this.rgb[2])).toString(16).substr(1)};var f=this,r=this.pickerMode.toLowerCase()===
"hvs"?1:0,v=false,m=jscolor.fetchElement(this.valueElement),q=jscolor.fetchElement(this.styleElement),y=false,z=false,x,w=1,D=2,C=4,B=8;jscolor.addEvent(d,"focus",function(){f.pickerOnfocus&&f.showPicker()});jscolor.addEvent(d,"blur",function(){if(v)v=false;else window.setTimeout(function(){if(!v){m===d&&f.importColor();f.pickerOnfocus&&f.hidePicker()}v=false},0)});if(m){t=function(){f.fromString(m.value,w)};jscolor.addEvent(m,"keyup",t);jscolor.addEvent(m,"input",t);jscolor.addEvent(m,"blur",I);
m.setAttribute("autocomplete","off")}if(q)q.jscStyle={backgroundColor:q.style.backgroundColor,color:q.style.color};switch(r){case 0:jscolor.requireImage("hs.png");break;case 1:jscolor.requireImage("hv.png")}jscolor.requireImage("cross.gif");jscolor.requireImage("arrow.gif");this.importColor()}};jscolor.install();
