$axure.loadCurrentPage({
  "url":"meadmin_treenav_staff.html",
  "generationDate":new Date(1396297422255.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ab6ae2d481804908ba73f70901384d0e",
    "type":"Axure:Page",
    "name":"MeAdmin_TreeNav_Staff",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkFrame",
                "description":"Open MeAdmin_Details_Pupil in Frame_Detailsbox",
                "linkType":"frame",
                "framesToTargets":[{
                    "framePath":["b152b808eea2422494e06a708832733f"],
                    "target":{
                      "targetType":"page",
                      "url":"meadmin_details_pupil.html",
                      "includeVariables":true}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"f4bc67711cdc4e4dbeb9e4dd6211321b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "size":{
              "width":302,
              "height":608},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":2,
              "color":{
                "r":51,
                "g":51,
                "b":51,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8f12363a3a748439a3a570a68c0449d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "size":{
                  "width":302,
                  "height":608},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":2,
                  "color":{
                    "r":51,
                    "g":51,
                    "b":51,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u10.png"}},
{
          "id":"8c0d559a23694e308e919570a8657abf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC5C5C5},
            "location":{
              "x":0,
              "y":571},
            "size":{
              "width":302,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fda7c7ca6d054bc99adb6714275ccea7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC5C5C5},
                "location":{
                  "x":0,
                  "y":571},
                "size":{
                  "width":302,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u12.png"}},
{
          "id":"e18ae2c69f26440e9bd555b537e2c8fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFCECECE},
{
                  "color":0xFFCECECE}]},
            "size":{
              "width":302,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24ce0cbf9deb448391700529d617af43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFCECECE},
{
                      "color":0xFFCECECE}]},
                "size":{
                  "width":302,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u14.png"}},
{
          "id":"eefedcdfc1784595ac2ac157cd583f74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC5C5C5},
            "location":{
              "x":0,
              "y":24},
            "size":{
              "width":302,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14d1b45056aa4c119baad1f400a0766f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC5C5C5},
                "location":{
                  "x":0,
                  "y":24},
                "size":{
                  "width":302,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_treenav_staff/u6.png"}},
{
          "id":"c93567db42e14421b92a68b8b734007b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Fet', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":6},
            "size":{
              "width":26,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93e994161be74651af57c0c50e2228b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Fet', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":6},
                "size":{
                  "width":26,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eacbc6c43abc4f0a954c32905ee0a9af",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":9,
              "y":29},
            "size":{
              "width":225,
              "height":18}},
          "adaptiveStyles":{
}},
{
          "id":"4db4f08d7ccd45d1b79126e92820d3f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF464646,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2}]},
            "location":{
              "x":240,
              "y":29},
            "size":{
              "width":56,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"394a439df40f418ca6b0fd6cd9db1cea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF464646,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2}]},
                "location":{
                  "x":240,
                  "y":29},
                "size":{
                  "width":56,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meoverview_treenav_01/u9.png"}},
{
          "id":"e7d78bde18cf40c196da3973dc779456",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Fet', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"bold",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFE6E6E6},
{
                  "color":0xFFE6E6E6},
{
                  "color":0xFFFAF9F9},
{
                  "color":0xFFFAF9F9}]},
            "location":{
              "x":0,
              "y":53},
            "size":{
              "width":302,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86a3d952c45644598e24fac6274cafd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Fet', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"bold",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFE6E6E6},
{
                      "color":0xFFE6E6E6},
{
                      "color":0xFFFAF9F9},
{
                      "color":0xFFFAF9F9}]},
                "location":{
                  "x":0,
                  "y":53},
                "size":{
                  "width":302,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/menu_overview/u24.png"}},
{
          "id":"162d29462795406ea7ee9b5084e569eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":77},
            "size":{
              "width":84,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d905c45b3fc0446390d8f341353ac350",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":77},
                "size":{
                  "width":84,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_treenav_staff/u15.png"}},
{
          "id":"b152b808eea2422494e06a708832733f",
          "label":"Frame_Detailsbox",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":0},
            "size":{
              "width":905,
              "height":612}},
          "adaptiveStyles":{
}},
{
          "id":"79589c85eacf430d9506b3dc5822eb79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":114},
            "size":{
              "width":154,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8f857b7be8b42c5b0d129f74bee394b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56,
                  "y":114},
                "size":{
                  "width":154,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_treenav_staff/u18.png"}},
{
          "id":"ba98c97a2ddd408f9c6cd9f1c913fd74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":39,
              "y":98},
            "size":{
              "width":109,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eac631a6aae48edb7c496ed0d8ca9bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":39,
                  "y":98},
                "size":{
                  "width":109,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c87111d73c494f79b4dd243a915268bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":100},
            "size":{
              "width":14,
              "height":9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c53b568c9679471cb0beba5a506864cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":100},
                "size":{
                  "width":14,
                  "height":9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_treenav_programme/u19.png"}},
{
          "id":"7e9feb44a4184fcfbe6fe4c89b3bcace",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":96},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8dd644841c347fcb58f110e3fd68cd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":96},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_treenav_programme/u27.png"}},
{
          "id":"9d678e7af7c0458cbcf2e47a83f378ac",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":98},
            "size":{
              "width":114,
              "height":13}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onContextMenu":{
              "description":"OnContextMenu",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle RC_educ.entity2/RCmenu_001",
                      "objectsToFades":[{
                          "objectPath":["e0ecf4846de94be6b373ef7254a4753a",
"d892128af251460da893ca2ad947d674"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"4b6673c3b8c7425c9730877f016e6e6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":57,
              "y":116},
            "size":{
              "width":139,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7630cc6f68f242ae8348c30949785f2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":57,
                  "y":116},
                "size":{
                  "width":139,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3405050b7c1d4a69b3c60ae6369a888d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":116},
            "size":{
              "width":149,
              "height":13}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"Open Link in Frame",
                      "linkType":"frame",
                      "framesToTargets":[]}]}]},
            "onContextMenu":{
              "description":"OnContextMenu",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle RC_Staff/RCmenu_001",
                      "objectsToFades":[{
                          "objectPath":["2ebff70845df4b16a5e24869c1634d70",
"5c76d48d03da4218a2f0ad49f5c07223"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"7104002988e0498a880d9f9dd6c30fe2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":114},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e149975b93034a9e90e50eae7cc417bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":114},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_treenav_staff/u30.png"}},
{
          "id":"e315a62dd5364be4b6538562d9040cd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":39,
              "y":80},
            "size":{
              "width":108,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11961dcccef046e5a6d45d59733f3c9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":39,
                  "y":80},
                "size":{
                  "width":108,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d4a8afc7440437e9749ee3554ad3fe2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":82},
            "size":{
              "width":14,
              "height":9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6241c0cf3a6645e7a89f0af279ccf212",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":82},
                "size":{
                  "width":14,
                  "height":9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_treenav_programme/u19.png"}},
{
          "id":"6a61e10de2b74d9fa66b13941a4f63b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":78},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b08f369fab0749bda023755b9f25b739",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":78},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_treenav_programme/u27.png"}},
{
          "id":"7d6dcbd167134307aa4c0823569c7b0c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":80},
            "size":{
              "width":114,
              "height":13}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onContextMenu":{
              "description":"OnContextMenu",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle RC_Educ.entity1/RCmenu_001",
                      "objectsToFades":[{
                          "objectPath":["2edbfb5af0024388b710558b94bf7739",
"d892128af251460da893ca2ad947d674"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"2edbfb5af0024388b710558b94bf7739",
          "label":"RC_Educ.entity1",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":78}},
          "adaptiveStyles":{
},
          "masterId":"7fdf1af720c34e3892c248ed20b27ff5"},
{
          "id":"2ebff70845df4b16a5e24869c1634d70",
          "label":"RC_Staff",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":116}},
          "adaptiveStyles":{
},
          "masterId":"a1f41d032f364107ad6bb30bac283f33"},
{
          "id":"e0ecf4846de94be6b373ef7254a4753a",
          "label":"RC_educ.entity2",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":95}},
          "adaptiveStyles":{
},
          "masterId":"7fdf1af720c34e3892c248ed20b27ff5"}]}},
  "masters":{
    "7fdf1af720c34e3892c248ed20b27ff5":{
      "packageId":"7fdf1af720c34e3892c248ed20b27ff5",
      "type":"Axure:Master",
      "name":"RC_Educ.entity",
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d892128af251460da893ca2ad947d674",
            "label":"RCmenu_001",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":false,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFEEEEEE},
              "size":{
                "width":98,
                "height":21},
              "visible":false},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7fc0e094c77f45108512307bc9fb1f0e",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":98,
                    "height":21}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"ba65c0594aa443379ab2a3732bee925b",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":98,
                        "height":21},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"751f323d6ae14a9091bb7279c88ad183",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":98,
                            "height":21},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "normal~":"resources/images/transparent.gif"}}]}]}]}},
    "a1f41d032f364107ad6bb30bac283f33":{
      "packageId":"a1f41d032f364107ad6bb30bac283f33",
      "type":"Axure:Master",
      "name":"RC_Staff",
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5c76d48d03da4218a2f0ad49f5c07223",
            "label":"RCmenu_001",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":false,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFEEEEEE},
              "size":{
                "width":116,
                "height":42},
              "visible":false},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eacd5c6839fd4daa8244489953cb50cb",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":116,
                    "height":42}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"97611926d4a54f6cbf66eb753f5aacc0",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":116,
                        "height":21},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9811206aeb8b4001ac533de57b7804a4",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":116,
                            "height":21},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"0cc3424b87354790a0df40ea629cf21a",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":21},
                      "size":{
                        "width":116,
                        "height":21},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fdbd62afc5da4457a2fe5ba8ed247bb9",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":21},
                          "size":{
                            "width":116,
                            "height":21},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]}]}}},
  "objectPaths":{
    "f4bc67711cdc4e4dbeb9e4dd6211321b":{
      "scriptId":"u0"},
    "b8f12363a3a748439a3a570a68c0449d":{
      "scriptId":"u1"},
    "8c0d559a23694e308e919570a8657abf":{
      "scriptId":"u2"},
    "fda7c7ca6d054bc99adb6714275ccea7":{
      "scriptId":"u3"},
    "e18ae2c69f26440e9bd555b537e2c8fa":{
      "scriptId":"u4"},
    "24ce0cbf9deb448391700529d617af43":{
      "scriptId":"u5"},
    "eefedcdfc1784595ac2ac157cd583f74":{
      "scriptId":"u6"},
    "14d1b45056aa4c119baad1f400a0766f":{
      "scriptId":"u7"},
    "c93567db42e14421b92a68b8b734007b":{
      "scriptId":"u8"},
    "93e994161be74651af57c0c50e2228b6":{
      "scriptId":"u9"},
    "eacbc6c43abc4f0a954c32905ee0a9af":{
      "scriptId":"u10"},
    "4db4f08d7ccd45d1b79126e92820d3f7":{
      "scriptId":"u11"},
    "394a439df40f418ca6b0fd6cd9db1cea":{
      "scriptId":"u12"},
    "e7d78bde18cf40c196da3973dc779456":{
      "scriptId":"u13"},
    "86a3d952c45644598e24fac6274cafd9":{
      "scriptId":"u14"},
    "162d29462795406ea7ee9b5084e569eb":{
      "scriptId":"u15"},
    "d905c45b3fc0446390d8f341353ac350":{
      "scriptId":"u16"},
    "b152b808eea2422494e06a708832733f":{
      "scriptId":"u17"},
    "79589c85eacf430d9506b3dc5822eb79":{
      "scriptId":"u18"},
    "b8f857b7be8b42c5b0d129f74bee394b":{
      "scriptId":"u19"},
    "ba98c97a2ddd408f9c6cd9f1c913fd74":{
      "scriptId":"u20"},
    "2eac631a6aae48edb7c496ed0d8ca9bc":{
      "scriptId":"u21"},
    "c87111d73c494f79b4dd243a915268bb":{
      "scriptId":"u22"},
    "c53b568c9679471cb0beba5a506864cb":{
      "scriptId":"u23"},
    "7e9feb44a4184fcfbe6fe4c89b3bcace":{
      "scriptId":"u24"},
    "b8dd644841c347fcb58f110e3fd68cd9":{
      "scriptId":"u25"},
    "9d678e7af7c0458cbcf2e47a83f378ac":{
      "scriptId":"u26"},
    "4b6673c3b8c7425c9730877f016e6e6b":{
      "scriptId":"u27"},
    "7630cc6f68f242ae8348c30949785f2c":{
      "scriptId":"u28"},
    "3405050b7c1d4a69b3c60ae6369a888d":{
      "scriptId":"u29"},
    "7104002988e0498a880d9f9dd6c30fe2":{
      "scriptId":"u30"},
    "e149975b93034a9e90e50eae7cc417bc":{
      "scriptId":"u31"},
    "e315a62dd5364be4b6538562d9040cd0":{
      "scriptId":"u32"},
    "11961dcccef046e5a6d45d59733f3c9d":{
      "scriptId":"u33"},
    "4d4a8afc7440437e9749ee3554ad3fe2":{
      "scriptId":"u34"},
    "6241c0cf3a6645e7a89f0af279ccf212":{
      "scriptId":"u35"},
    "6a61e10de2b74d9fa66b13941a4f63b7":{
      "scriptId":"u36"},
    "b08f369fab0749bda023755b9f25b739":{
      "scriptId":"u37"},
    "7d6dcbd167134307aa4c0823569c7b0c":{
      "scriptId":"u38"},
    "2edbfb5af0024388b710558b94bf7739":{
      "scriptId":"u39",
      "d892128af251460da893ca2ad947d674":{
        "scriptId":"u40"},
      "7fc0e094c77f45108512307bc9fb1f0e":{
        "scriptId":"u41"},
      "ba65c0594aa443379ab2a3732bee925b":{
        "scriptId":"u42"},
      "751f323d6ae14a9091bb7279c88ad183":{
        "scriptId":"u43"}},
    "2ebff70845df4b16a5e24869c1634d70":{
      "scriptId":"u44",
      "5c76d48d03da4218a2f0ad49f5c07223":{
        "scriptId":"u45"},
      "eacd5c6839fd4daa8244489953cb50cb":{
        "scriptId":"u46"},
      "97611926d4a54f6cbf66eb753f5aacc0":{
        "scriptId":"u47"},
      "9811206aeb8b4001ac533de57b7804a4":{
        "scriptId":"u48"},
      "0cc3424b87354790a0df40ea629cf21a":{
        "scriptId":"u49"},
      "fdbd62afc5da4457a2fe5ba8ed247bb9":{
        "scriptId":"u50"}},
    "e0ecf4846de94be6b373ef7254a4753a":{
      "scriptId":"u51",
      "d892128af251460da893ca2ad947d674":{
        "scriptId":"u52"},
      "7fc0e094c77f45108512307bc9fb1f0e":{
        "scriptId":"u53"},
      "ba65c0594aa443379ab2a3732bee925b":{
        "scriptId":"u54"},
      "751f323d6ae14a9091bb7279c88ad183":{
        "scriptId":"u55"}}}});