<?php
include("model/core.php");
include("model/pupil.php");
include("model/studyGroup.php");
include("model/studyGroup_pupil.php");
include("model/objective_pupil.php");
include("model/objectiveName.php");
include("model/objectiveWeight.php");
include("model/group.php");
include("model/group_pupil.php");
include("model/assignmentOrPerformance.php");
include("model/assignment.php");
include("model/perfUnits.php");
include("model/assignPerfUnits.php");
include("model/system_settings_table.php");
include("model/hideGroup.php");
include("model/HideAssignment.php");
include("model/HidePerformance.php");
include("model/hideObjective.php");
include("model/hideColumn.php");
include("model/hidePupil.php");
?>