tinymce.addI18n('sv_SE',{
"Cut": "Klipp ut",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Din browser st\u00f6der inte direkt acess till klippboken. V\u00e4nligen anv\u00e4nd Ctrl+X\/C\/V kortkomandon i st\u00e4llet.",
"Paste": "Klistra in",
"Close": "St\u00e4ng",
"Align right": "H\u00f6gerst\u00e4ll",
"New document": "Nytt dokument",
"Numbered list": "Nummerlista",
"Increase indent": "\u00d6ka indrag",
"Formats": "Format",
"Select all": "Markera allt",
"Undo": "\u00c5ngra",
"Strikethrough": "Genomstruken",
"Bullet list": "Punktlista",
"Superscript": "Upph\u00f6jd text",
"Clear formatting": "Avformattera",
"Subscript": "Neds\u00e4nkt text",
"Redo": "G\u00f6r om",
"Ok": "Ok",
"Bold": "Fetstil",
"Italic": "Kurisvstil",
"Align center": "Centrera",
"Decrease indent": "Minska indrag",
"Underline": "Understruken",
"Cancel": "Avbryt",
"Justify": "Justera",
"Copy": "Kopiera",
"Align left": "V\u00e4nsterst\u00e4ll",
"Visual aids": "Visuella hj\u00e4lpmedel",
"Lower Greek": "Grekiska gemener",
"Square": "Fyrkant",
"Default": "Orginal",
"Lower Alpha": "Gemener",
"Circle": "Cirkel",
"Disc": "Disk",
"Upper Alpha": "Varsaler",
"Upper Roman": "Romerskaversaler",
"Lower Roman": "Romerskagemener",
"Name": "Namn",
"Anchor": "Ankare",
"You have unsaved changes are you sure you want to navigate away?": "Du har f\u00f6r\u00e4ndringar som du inte har sparat. \u00c4r du s\u00e4ker p\u00e5 att du vill navigera vidare?",
"Restore last draft": "\u00c5terst\u00e4ll senaste utkast",
"Special character": "Specialtecken",
"Source code": "K\u00e4llk\u00e5d",
"Right to left": "H\u00f6ger till v\u00e4nster",
"Left to right": "V\u00e4nster till h\u00f6ger",
"Emoticons": "Emoticons",
"Robots": "Robotar",
"Document properties": "Dokumentegenskaper",
"Title": "Titel",
"Keywords": "Nyckelord",
"Encoding": "Encoding",
"Description": "Beskrivning",
"Author": "F\u00f6rfattare",
"Fullscreen": "Fullsk\u00e4rm",
"Horizontal line": "Horizontell linie",
"Source": "K\u00e4lla",
"Constrain proportions": "Begr\u00e4nsa proportioner",
"Dimensions": "Dimensioner",
"Insert\/edit image": "Infoga\/redigera bild",
"Image description": "Bildbeskrivning",
"Insert date\/time": "Infoga datum\/tid",
"Url": "Url",
"Text to display": "Text att visa",
"Insert link": "Infoga l\u00e4nk",
"New window": "Nytt f\u00f6nster",
"None": "Ingen",
"Target": "M\u00e5l",
"Insert\/edit link": "Infoga\/redigera l\u00e4nk",
"Insert\/edit video": "Infoga\/redigera video",
"General": "Generella",
"Poster": "Affish",
"Alternative source": "Alternativ k\u00e4lla",
"Paste your embed code below:": "Klistra in din inb\u00e4ddningsk\u00e5d nedan:",
"Insert video": "Infoga video",
"Embed": "Inb\u00e4ddning",
"Nonbreaking space": "Avbrottsfritt mellanrum",
"Page break": "Sydbrytning",
"Preview": "F\u00f6rhandsgranska",
"Print": "Skriv ut",
"Save": "Spara",
"Could not find the specified string.": "Kunde inte hitta den specifierade st\u00e4ngen.",
"Replace": "Ers\u00e4tt",
"Next": "N\u00e4sta",
"Whole words": "Hela ord",
"Find and replace": "S\u00f6k och ers\u00e4tt",
"Replace with": "Ers\u00e4tt med",
"Find": "S\u00f6k",
"Replace all": "Ers\u00e4tt alla",
"Match case": "Matcha gemener\/versaler",
"Prev": "F\u00f6reg\u00e5ende",
"Spellcheck": "R\u00e4ttstava",
"Finish": "Avsluta",
"Ignore all": "Ignorera alla",
"Ignore": "Ignorera",
"Insert row before": "Infoga rad f\u00f6re",
"Rows": "Rader",
"Height": "H\u00f6jd",
"Paste row after": "Klistra in rad efter",
"Alignment": "Justering",
"Column group": "Kolumngrupp",
"Row": "Rad",
"Insert column before": "Infoga kollumn f\u00f6re",
"Split cell": "Bryt is\u00e4r celler",
"Cell padding": "Cellpaddning",
"Cell spacing": "Cellmellanrum",
"Row type": "Radtyp",
"Insert table": "Infoga tabell",
"Body": "Kropp",
"Caption": "Rubrik",
"Footer": "Fot",
"Delete row": "Radera rad",
"Paste row before": "Klista in rad f\u00f6re",
"Scope": "Omf\u00e5ng",
"Delete table": "Radera tabell",
"Header cell": "Huvudcell",
"Column": "Kolumn",
"Cell": "Cell",
"Header": "Huvud",
"Border": "Ram",
"Cell type": "Celltyp",
"Copy row": "Kopiera rad",
"Row properties": "Radegenskaper",
"Table properties": "Tabell egenskaper",
"Row group": "Radgrupp",
"Right": "H\u00f6ger",
"Insert column after": "Infoga kolumn efter",
"Cols": "Kolumner",
"Insert row after": "Infoga rad efter",
"Width": "Bredd",
"Cell properties": "Cellegenskaper",
"Left": "V\u00e4nster",
"Cut row": "Klipp ut rad",
"Delete column": "Radera kolumn",
"Center": "Centrum",
"Merge cells": "Sammanfoga celler",
"Insert template": "Infoga mall",
"Templates": "Mallar",
"Background color": "Bakgrundsf\u00e4rg",
"Text color": "Textf\u00e4rg",
"Show blocks": "Visa block",
"Show invisible characters": "Visa onsynliga tecken",
"Words: {0}": "Ord: {0}",
"Insert": "Infoga",
"File": "Fil",
"Edit": "Redigera",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Textredigerare. Tryck ALT-F9 f\u00f6r menyn. Tryck ALT-F10 f\u00f6r verktygsrader. Tryck ALT-0 f\u00f6r hj\u00e4lp.",
"Tools": "Verktyg",
"View": "Vy",
"Table": "Tabell",
"Format": "Format"
});