$axure.loadCurrentPage({
  "url":"meadmin_details_programme_studygroup_list_headerfoot.html",
  "generationDate":new Date(1396297425579.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c352b363b67c46058f36bc0365ee5550",
    "type":"Axure:Page",
    "name":"MeAdmin_Details_programme_Studygroup list_headerfoot",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkFrame",
                "description":"Open MeAdmin_Details_studygroups_members in grid_frame_01",
                "linkType":"frame",
                "framesToTargets":[{
                    "framePath":["d76416108575457a9a016beed883d1f0"],
                    "target":{
                      "targetType":"page",
                      "url":"meadmin_details_studygroups_members.html",
                      "includeVariables":true}}]},
{
                "action":"setFunction",
                "description":"Set is selected of studygroup members equal to &quot;true&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["a5c51c8a956643aa98bcfe9a03cb2acd"]},
{
                          "exprType":"stringLiteral",
                          "value":"true",
                          "stos":[]}]}]}}]}]}},
    "diagram":{
      "objects":[{
          "id":"1f7a5cc7e741468db04345844acbca4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "size":{
              "width":899,
              "height":608},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":2,
              "color":{
                "r":51,
                "g":51,
                "b":51,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11e9eb3ed82c45d29f5ee59d6555efe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "size":{
                  "width":899,
                  "height":608},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":2,
                  "color":{
                    "r":51,
                    "g":51,
                    "b":51,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u0.png"}},
{
          "id":"4fef6e6516c347f290f397f40d3c21fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFCECECE},
{
                  "color":0xFFCECECE}]},
            "size":{
              "width":900,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57f1a2d03a55468696f34383f8e24cd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFCECECE},
{
                      "color":0xFFCECECE}]},
                "size":{
                  "width":900,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u4.png"}},
{
          "id":"79c831d9a2ff4c38be8f6df8f1683225",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Fet', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":28,
              "y":6},
            "size":{
              "width":85,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da30f2e37aa74fb991504a8d4ddc040c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Fet', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":6},
                "size":{
                  "width":85,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56524483db3b45cd936c629b905c5db4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":6},
            "size":{
              "width":13,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f16012fa08840b9b8112f334227a032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":6},
                "size":{
                  "width":13,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u8.png"}},
{
          "id":"e075e77ef1df43fca37443a6fc0e8b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1EE},
            "location":{
              "x":1,
              "y":25},
            "size":{
              "width":897,
              "height":41},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e25e581a75542c6a879f206e95aa9fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1EE},
                "location":{
                  "x":1,
                  "y":25},
                "size":{
                  "width":897,
                  "height":41},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u8.png"}},
{
          "id":"43f6be4cf036422b8107843e2475f3bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":365,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7c25a09c31643e3943ded7b7a923b1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":365,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31bb0165514c48908162c7713ee418ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC5C5C5},
            "location":{
              "x":0,
              "y":571},
            "size":{
              "width":899,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b302365985c44e1c81577b15fd9ef33c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC5C5C5},
                "location":{
                  "x":0,
                  "y":571},
                "size":{
                  "width":899,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/menu_overview/u2.png"}},
{
          "id":"0a0864c915c64fc58b37bfda30c25b8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF464646,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2}]},
            "location":{
              "x":11,
              "y":575},
            "size":{
              "width":100,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56795fde551340238ac49f4065c49dcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF464646,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2}]},
                "location":{
                  "x":11,
                  "y":575},
                "size":{
                  "width":100,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_programme_studygroup_list_headerfoot/u14.png"}},
{
          "id":"caa3a129eda749e7893fd4902887aede",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF464646,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2}]},
            "location":{
              "x":823,
              "y":575},
            "size":{
              "width":65,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"003ff9a7ec6942c49b8d872978cba11c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF464646,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2}]},
                "location":{
                  "x":823,
                  "y":575},
                "size":{
                  "width":65,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u14.png"}},
{
          "id":"e06ff81c1e844859a7eaf78d615a30de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF464646,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFF2F2F2},
{
                  "color":0xFFF2F2F2}]},
            "location":{
              "x":116,
              "y":575},
            "size":{
              "width":149,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99e20169403249beb1f23345a684bdcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF464646,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2}]},
                "location":{
                  "x":116,
                  "y":575},
                "size":{
                  "width":149,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_programme_studygroup_list_headerfoot/u18.png"}},
{
          "id":"c9eaa682be584e14b44f1f9ac3fdac95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":40,
              "y":48},
            "size":{
              "width":416,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"650d3de7e3404e93ba5709b0016a1db7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":48},
                "size":{
                  "width":416,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68c2e15d67644c27b0de20228e989340",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":32},
            "size":{
              "width":27,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05e750e0dc3b4cdeb1eb757dc24ca622",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":32},
                "size":{
                  "width":27,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u20.png"}},
{
          "id":"d76416108575457a9a016beed883d1f0",
          "label":"grid_frame_01",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":899,
              "height":482}},
          "adaptiveStyles":{
}},
{
          "id":"bda16c5b9c9c4f36aac291e088fc0141",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFCECECE},
{
                  "color":0xFFCECECE}]},
            "location":{
              "x":0,
              "y":66},
            "size":{
              "width":900,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0198ae55d45f4b3a8f1c33a952e1ace3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFCECECE},
{
                      "color":0xFFCECECE}]},
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":900,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/meadmin_details_educ_entity_headerfoot/u23.png"}},
{
          "id":"9146c8383b02498dbd7cda022fcd21c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Fet', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":11,
              "y":72},
            "size":{
              "width":132,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11d5adc2688142058135a2175033d5c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Fet', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":72},
                "size":{
                  "width":132,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5c51c8a956643aa98bcfe9a03cb2acd",
          "label":"studygroup members",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}},
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFB9BCC4},
            "location":{
              "x":764,
              "y":69},
            "size":{
              "width":132,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71aa52fdb7ca4f23bef1363868b830e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}},
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFB9BCC4},
                "location":{
                  "x":764,
                  "y":69},
                "size":{
                  "width":132,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"Open MeAdmin_Details_studygroups_members in grid_frame_01",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["d76416108575457a9a016beed883d1f0"],
                          "target":{
                            "targetType":"page",
                            "url":"meadmin_details_studygroups_members.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/meadmin_details_programme_studygroup_list_headerfoot/studygroup_members_u29.png",
            "selected~":"images/meadmin_details_programme_studygroup_list_headerfoot/studygroup_members_u29_selected.png",
            "mouseOver~":"images/meadmin_details_programme_studygroup_list_headerfoot/studygroup_members_u29_selected.png"}},
{
          "id":"6a7280bfcd9143efbe8c620311659970",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":83},
            "size":{
              "width":899,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8B9BA8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/meadmin_details_educ_entity_headerfoot/u29_line.png"}},
{
          "id":"78d2977f780248eba9064c4296ff245b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}},
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B9BA8}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFB9BCC4},
            "location":{
              "x":645,
              "y":69},
            "size":{
              "width":124,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48574bed894f42f59954f6923f93ac5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"f8af646f840f43adb5cc197c7e0d84c9",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}},
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF8B9BA8}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFB9BCC4},
                "location":{
                  "x":645,
                  "y":69},
                "size":{
                  "width":124,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"Open MeAdmin_Details_studygroups_plan in grid_frame_01",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["d76416108575457a9a016beed883d1f0"],
                          "target":{
                            "targetType":"page",
                            "url":"meadmin_details_studygroups_plan.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/meadmin_details_programme_studygroup_list_headerfoot/u32.png",
            "selected~":"images/meadmin_details_programme_studygroup_list_headerfoot/u32_selected.png",
            "mouseOver~":"images/meadmin_details_programme_studygroup_list_headerfoot/u32_selected.png"}},
{
          "id":"e22cab093fe9452f8b7436f24d38c1b9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"95c9cf50f331461dbd090a35ed2d978f"}]}},
  "masters":{
    "95c9cf50f331461dbd090a35ed2d978f":{
      "packageId":"95c9cf50f331461dbd090a35ed2d978f",
      "type":"Axure:Master",
      "name":"Studygroup_list_action",
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"87a7e91cf8fa4ff88aaf4ef6148913bf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF464646,
                "opacity":1},
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFCCCCCC},
{
                    "color":0xFFCCCCCC},
{
                    "color":0xFFF2F2F2},
{
                    "color":0xFFF2F2F2}]},
              "location":{
                "x":831,
                "y":29},
              "size":{
                "width":58,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF666666},
              "cornerRadiusTopLeft":"1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54acb0bfdaa84f2d8f72cc006fc160de",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF464646,
                    "opacity":1},
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFCCCCCC},
{
                        "color":0xFFCCCCCC},
{
                        "color":0xFFF2F2F2},
{
                        "color":0xFFF2F2F2}]},
                  "location":{
                    "x":831,
                    "y":29},
                  "size":{
                    "width":58,
                    "height":16},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "cornerRadiusTopLeft":"1"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle RCmenu_001",
                        "objectsToFades":[{
                            "objectPath":["322986e6b6ab4da690dd782258ae802a"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/meadmin_details_educ_entity_headerfoot/u35.png"}},
{
            "id":"f4546c6a67e941909b0ec1f5f964890e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":838,
                "y":34},
              "size":{
                "width":7,
                "height":7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b7c4081b6900427885c8256441fadd2c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":838,
                    "y":34},
                  "size":{
                    "width":7,
                    "height":7}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle RCmenu_001",
                        "objectsToFades":[{
                            "objectPath":["322986e6b6ab4da690dd782258ae802a"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/meadmin_details_educ_entity_headerfoot/u37.png"}},
{
            "id":"322986e6b6ab4da690dd782258ae802a",
            "label":"RCmenu_001",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":false,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFEEEEEE},
              "location":{
                "x":590,
                "y":29},
              "size":{
                "width":195,
                "height":168},
              "visible":false},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7fa4d1f2f9634267b10c72612b725bdf",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":195,
                    "height":168}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"8f13930202f74ce4bc1ea93e31852485",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":195,
                        "height":20},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1a8c3204043a425a89b8f90f7ff84200",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":195,
                            "height":20},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"41286e0a870243f3a388dc9e6086da81",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":120},
                      "size":{
                        "width":195,
                        "height":21},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4827ae4c6ca048978ca22c84a3044f9f",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":120},
                          "size":{
                            "width":195,
                            "height":21},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"2a9d4a08b04d4f578fbbe92e23703a53",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":141},
                      "size":{
                        "width":195,
                        "height":27},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c8ca43fbc8c14029b0a186b5b3500377",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":141},
                          "size":{
                            "width":195,
                            "height":27},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"0ce7c5d741b240828c79b14b8d4640c2",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":195,
                        "height":20},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4eec090bb22e40cfa3e097aecef304c3",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":195,
                            "height":20},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"80869bc8afc746969840220f5ebc5944",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":60},
                      "size":{
                        "width":195,
                        "height":20},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6676802b340048e7b7aeb98a0c597532",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":60},
                          "size":{
                            "width":195,
                            "height":20},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"fdd63cd43f7a42de9315c592b4e1fb5d",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":195,
                        "height":20},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d3f28cb4455d4712838f2243dabfa70f",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":195,
                            "height":20},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"7b12482f052e47b2acdb83f1d0339703",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":100},
                      "size":{
                        "width":195,
                        "height":20},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"cb4bd45de3534990990135ed6cef9d96",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":100},
                          "size":{
                            "width":195,
                            "height":20},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b1732932f46c443fbc4fcc97f37f9fea",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "lineSpacing":"6px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":20},
                      "size":{
                        "width":195,
                        "height":20},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8823fb128f7a4bad916eae890f82a0d6",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":20},
                          "size":{
                            "width":195,
                            "height":20},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]},
{
                "id":"16d813b1f2114f7d9ad146803467a774",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFEEEEEE},
                  "location":{
                    "x":195,
                    "y":141},
                  "size":{
                    "width":59,
                    "height":40},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"f6f081474e504dd08bfe821c2ac548bb",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":59,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1f96fc2c663d4ac3a63afea640e43173",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":59,
                            "height":20},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"05de40ee30a74027b7628f318c38d89b",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"10px",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "lineSpacing":"6px",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":59,
                                "height":20},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFCCCCCC}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"245c09e02dec430ca8792ddffa0ed51a",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":20},
                          "size":{
                            "width":59,
                            "height":20},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"f0d6e300bd7b44baa9c2bd0fe1a1dc61",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"10px",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "lineSpacing":"6px",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":20},
                              "size":{
                                "width":59,
                                "height":20},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFCCCCCC}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}}]}],
                "parentCellId":"2a9d4a08b04d4f578fbbe92e23703a53"},
{
                "id":"038de88bbc0a4706957b1800f4bd34d1",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFEEEEEE},
                  "location":{
                    "x":195,
                    "y":120},
                  "size":{
                    "width":82,
                    "height":40},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"f0f0dd731898427aa4752cddc3b92859",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":82,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3372d7ebbb474d1382bd9c31880095ba",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":82,
                            "height":20},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"d0aa75d94de440caa3ec49f57f322ac0",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"10px",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "lineSpacing":"6px",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":82,
                                "height":20},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFCCCCCC}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}},
{
                        "id":"c7ff3f275b0e416bb8f773d1d64c4b88",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "lineSpacing":"6px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":20},
                          "size":{
                            "width":82,
                            "height":20},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"2b61af14bf484746b046a4a1fb86bbf9",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"10px",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "lineSpacing":"6px",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":20},
                              "size":{
                                "width":82,
                                "height":20},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFCCCCCC}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"resources/images/transparent.gif"}}]}],
                "parentCellId":"41286e0a870243f3a388dc9e6086da81"}]}]}}},
  "objectPaths":{
    "1f7a5cc7e741468db04345844acbca4c":{
      "scriptId":"u0"},
    "11e9eb3ed82c45d29f5ee59d6555efe1":{
      "scriptId":"u1"},
    "4fef6e6516c347f290f397f40d3c21fa":{
      "scriptId":"u2"},
    "57f1a2d03a55468696f34383f8e24cd4":{
      "scriptId":"u3"},
    "79c831d9a2ff4c38be8f6df8f1683225":{
      "scriptId":"u4"},
    "da30f2e37aa74fb991504a8d4ddc040c":{
      "scriptId":"u5"},
    "56524483db3b45cd936c629b905c5db4":{
      "scriptId":"u6"},
    "2f16012fa08840b9b8112f334227a032":{
      "scriptId":"u7"},
    "e075e77ef1df43fca37443a6fc0e8b2a":{
      "scriptId":"u8"},
    "8e25e581a75542c6a879f206e95aa9fc":{
      "scriptId":"u9"},
    "43f6be4cf036422b8107843e2475f3bf":{
      "scriptId":"u10"},
    "a7c25a09c31643e3943ded7b7a923b1f":{
      "scriptId":"u11"},
    "31bb0165514c48908162c7713ee418ef":{
      "scriptId":"u12"},
    "b302365985c44e1c81577b15fd9ef33c":{
      "scriptId":"u13"},
    "0a0864c915c64fc58b37bfda30c25b8d":{
      "scriptId":"u14"},
    "56795fde551340238ac49f4065c49dcc":{
      "scriptId":"u15"},
    "caa3a129eda749e7893fd4902887aede":{
      "scriptId":"u16"},
    "003ff9a7ec6942c49b8d872978cba11c":{
      "scriptId":"u17"},
    "e06ff81c1e844859a7eaf78d615a30de":{
      "scriptId":"u18"},
    "99e20169403249beb1f23345a684bdcb":{
      "scriptId":"u19"},
    "c9eaa682be584e14b44f1f9ac3fdac95":{
      "scriptId":"u20"},
    "650d3de7e3404e93ba5709b0016a1db7":{
      "scriptId":"u21"},
    "68c2e15d67644c27b0de20228e989340":{
      "scriptId":"u22"},
    "05e750e0dc3b4cdeb1eb757dc24ca622":{
      "scriptId":"u23"},
    "d76416108575457a9a016beed883d1f0":{
      "scriptId":"u24"},
    "bda16c5b9c9c4f36aac291e088fc0141":{
      "scriptId":"u25"},
    "0198ae55d45f4b3a8f1c33a952e1ace3":{
      "scriptId":"u26"},
    "9146c8383b02498dbd7cda022fcd21c7":{
      "scriptId":"u27"},
    "11d5adc2688142058135a2175033d5c6":{
      "scriptId":"u28"},
    "a5c51c8a956643aa98bcfe9a03cb2acd":{
      "scriptId":"u29"},
    "71aa52fdb7ca4f23bef1363868b830e8":{
      "scriptId":"u30"},
    "6a7280bfcd9143efbe8c620311659970":{
      "scriptId":"u31"},
    "78d2977f780248eba9064c4296ff245b":{
      "scriptId":"u32"},
    "48574bed894f42f59954f6923f93ac5d":{
      "scriptId":"u33"},
    "e22cab093fe9452f8b7436f24d38c1b9":{
      "scriptId":"u34",
      "87a7e91cf8fa4ff88aaf4ef6148913bf":{
        "scriptId":"u35"},
      "54acb0bfdaa84f2d8f72cc006fc160de":{
        "scriptId":"u36"},
      "f4546c6a67e941909b0ec1f5f964890e":{
        "scriptId":"u37"},
      "b7c4081b6900427885c8256441fadd2c":{
        "scriptId":"u38"},
      "322986e6b6ab4da690dd782258ae802a":{
        "scriptId":"u39"},
      "7fa4d1f2f9634267b10c72612b725bdf":{
        "scriptId":"u40"},
      "8f13930202f74ce4bc1ea93e31852485":{
        "scriptId":"u41"},
      "1a8c3204043a425a89b8f90f7ff84200":{
        "scriptId":"u42"},
      "b1732932f46c443fbc4fcc97f37f9fea":{
        "scriptId":"u43"},
      "8823fb128f7a4bad916eae890f82a0d6":{
        "scriptId":"u44"},
      "0ce7c5d741b240828c79b14b8d4640c2":{
        "scriptId":"u45"},
      "4eec090bb22e40cfa3e097aecef304c3":{
        "scriptId":"u46"},
      "80869bc8afc746969840220f5ebc5944":{
        "scriptId":"u47"},
      "6676802b340048e7b7aeb98a0c597532":{
        "scriptId":"u48"},
      "fdd63cd43f7a42de9315c592b4e1fb5d":{
        "scriptId":"u49"},
      "d3f28cb4455d4712838f2243dabfa70f":{
        "scriptId":"u50"},
      "7b12482f052e47b2acdb83f1d0339703":{
        "scriptId":"u51"},
      "cb4bd45de3534990990135ed6cef9d96":{
        "scriptId":"u52"},
      "41286e0a870243f3a388dc9e6086da81":{
        "scriptId":"u53"},
      "4827ae4c6ca048978ca22c84a3044f9f":{
        "scriptId":"u54"},
      "2a9d4a08b04d4f578fbbe92e23703a53":{
        "scriptId":"u55"},
      "c8ca43fbc8c14029b0a186b5b3500377":{
        "scriptId":"u56"},
      "16d813b1f2114f7d9ad146803467a774":{
        "scriptId":"u57"},
      "f6f081474e504dd08bfe821c2ac548bb":{
        "scriptId":"u58"},
      "1f96fc2c663d4ac3a63afea640e43173":{
        "scriptId":"u59"},
      "05de40ee30a74027b7628f318c38d89b":{
        "scriptId":"u60"},
      "245c09e02dec430ca8792ddffa0ed51a":{
        "scriptId":"u61"},
      "f0d6e300bd7b44baa9c2bd0fe1a1dc61":{
        "scriptId":"u62"},
      "038de88bbc0a4706957b1800f4bd34d1":{
        "scriptId":"u63"},
      "f0f0dd731898427aa4752cddc3b92859":{
        "scriptId":"u64"},
      "3372d7ebbb474d1382bd9c31880095ba":{
        "scriptId":"u65"},
      "d0aa75d94de440caa3ec49f57f322ac0":{
        "scriptId":"u66"},
      "c7ff3f275b0e416bb8f773d1d64c4b88":{
        "scriptId":"u67"},
      "2b61af14bf484746b046a4a1fb86bbf9":{
        "scriptId":"u68"}}}});